{% set name = "kcombu_bss" %}
{% set version = "2022.06.10" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
  git_url: https://github.com/michellab/kcombu_bss.git
  git_tag: devel

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}

about:
  home: https://github.com/michellab/kcombu_bss
  license: BSD-3-Clause
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: A tool for flexible transformation of a target molecule onto a reference molecule.
  dev_url: https://github.com/michellab/kcombu_bss
  doc_url: https://github.com/michellab/kcombu_bss
  description: A tool for flexible transformation of a target molecule onto a reference molecule.

extra:
  recipe-maintainers:
    - chryswoods
    - jmichel80
    - lohedges
