/*
 
 <ioMOL2.c> 

==============================================================================
Copyright 2018  Takeshi Kawabata.  All rights reserved.

This software is released under the three-clause BSD License, see LICENSE.txt.
==============================================================================

 
  input/output functions for MOL2 files

>> Example of MOL2 file  taken from the ZINC database <<
@<TRIPOS>MOLECULE
ZINC15633213
   11    10     0     0     0
SMALL
USER_CHARGES

@<TRIPOS>ATOM
      1 H1          0.0021   -0.0041    0.0020 H         1 <0>         0.1232
      2 C1         -0.0127    1.0858    0.0080 C.3       1 <0>        -0.0495
      3 H2          1.0099    1.4631    0.0003 H         1 <0>         0.1232
      4 H3         -0.5399    1.4469   -0.8751 H         1 <0>         0.1255
      5 N1         -0.7003    1.5596    1.2166 N.4       1 <0>        -0.5102
      6 C2          0.0102    1.0729    2.4067 C.3       1 <0>        -0.0495
      7 H4         -0.5000    1.4245    3.3035 H         1 <0>         0.1255
      8 H5          0.0250   -0.0169    2.4007 H         1 <0>         0.1232
      9 H6          1.0328    1.4502    2.3990 H         1 <0>         0.1232
     10 H7         -0.7140    2.5685    1.2222 H         1 <0>         0.4327
     11 H8         -1.6469    1.2103    1.2238 H         1 <0>         0.4327
@<TRIPOS>BOND
     1    1    2 1
     2    2    3 1
     3    2    4 1
     4    2    5 1
     5    5    6 1
     6    5   10 1
     7    5   11 1
     8    6    7 1
     9    6    8 1
    10    6    9 1

>> Example of MOL2 file generated by the babel program  <<
@<TRIPOS>MOLECULE
/DB/LIGAND-EXPO/SDF/BEN
 9 9 0 0 0
SMALL
GASTEIGER
Energy = 0

@<TRIPOS>ATOM
      1 C           0.3333    0.0000    0.0000 C.ar    1  LIG1        0.0975
      2 C          -0.4167   -1.2990    0.0000 C.ar    1  LIG1        0.0080
      3 C          -1.9167   -1.2990    0.0000 C.ar    1  LIG1        0.0003
      4 C          -2.6667    0.0000    0.0000 C.ar    1  LIG1        0.0000
      5 C          -1.9167    1.2990    0.0000 C.ar    1  LIG1        0.0003
      6 C          -0.4167    1.2990    0.0000 C.ar    1  LIG1        0.0080
      7 C           1.8333   -0.0000    0.0000 C.2     1  LIG1        0.4766
      8 N           2.5833    1.2990    0.0000 N.pl3   1  LIG1        0.2047
      9 N           2.5833   -1.2990    0.0000 N.pl3   1  LIG1        0.2047
@<TRIPOS>BOND
     1     1     2   ar
     2     1     6   ar
     3     1     7    1
     4     2     3   ar
     5     3     4   ar
     6     4     5   ar
     7     5     6   ar
     8     7     8    2
     9     7     9    1

>> Example of MOL2 file taken from the myPresto MATRIX.tar.gz  <<
@<TRIPOS>MOLECULE
conf1.mol2
 8 7 0 0 0
SMALL
NO_CHARGES

@<TRIPOS>ATOM
      1 C          14.9610   22.8170    4.7260 C.2     0  <1>         0.5670
      2 O          15.8360   22.6310    5.6100 O.2     0  <1>        -0.6314
      3 N          14.2950   23.9210    4.5450 N.am    0  <1>        -0.8779
      4 H          13.8110   24.0770    3.6840 H       0  <1>         0.3672
      5 H          14.2680   24.6130    5.2670 H       0  <1>         0.3672
      6 C          14.9360   21.8010    3.5270 C.2     0  <1>         0.8405
      7 O          14.0870   22.0030    2.6050 O.co2   0  <1>        -0.8163
      8 O          16.1090   21.3460    3.3700 O.co2   0  <1>        -0.8163
@<TRIPOS>BOND
     1     1     2    2
     2     1     3    1
     3     1     6    1
     4     3     4    1
     5     3     5    1
     6     6     7    1
     7     6     8    2


>> Example of MOL2 file taken from the myPresto MATRIX.tar.gz  <<
@<TRIPOS>MOLECULE
lig.mol2
 24 23 0 0 0
SMALL
GASTEIGER

@<TRIPOS>ATOM
   1 N        52.9070    16.5460    -4.3540 N.4     1   UNK         0.2274
   2 CA       51.9980    17.6810    -4.7520 C.3     1   UNK         0.0554
   3 C        52.5700    18.7580    -5.6730 C.2     1   UNK         0.2835
   4 O        53.6330    18.7010    -6.3740 O.2     1   UNK        -0.2675
   5 CB       52.0280    18.4720    -3.3480 C.3     1   UNK         0.0013
   6 CG       52.9200    17.7210    -2.3660 C.3     1   UNK        -0.0412
   7 CD1      54.2770    17.6690    -3.1420 C.3     1   UNK        -0.0625
   8 CD2      53.0310    18.2540    -0.9470 C.3     1   UNK        -0.0625
   9 N2       51.8440    19.8300    -5.6540 N.am    1   UNK        -0.1928
  10 ON2      52.4760    20.7250    -6.4920 O.3     1   UNK        -0.2950
  11 H1       53.2005    16.6793    -3.3863 H       1   UNK         0.2002
  12 H2       52.3992    15.6661    -4.4454 H       1   UNK         0.2002
  13 H3       53.7220    16.5425    -4.9674 H       1   UNK         0.2002
  14 H4       50.9393    17.3156    -4.7574 H       1   UNK         0.0949
  15 H5       52.4341    19.5018    -3.5183 H       1   UNK         0.0327
  16 H6       50.9859    18.5346    -2.9424 H       1   UNK         0.0327
  17 H7       52.6406    16.6365    -2.3755 H       1   UNK         0.0298
  18 H8       54.4929    16.6079    -3.4282 H       1   UNK         0.0232
  19 H9       54.1959    18.3036    -4.0613 H       1   UNK         0.0232
  20 H10      55.0912    18.0590    -2.4792 H       1   UNK         0.0232
  21 H11      52.8042    17.4260    -0.2277 H       1   UNK         0.0232
  22 H12      54.0723    18.6309    -0.7795 H       1   UNK         0.0232
  23 H13      52.2964    19.0887    -0.8125 H       1   UNK         0.0232
  24 H14      50.9979    19.8629    -5.0853 H       1   UNK         0.1824
@<TRIPOS>BOND
   1   1   2   1
   2   2   3   1
   3   2   5   1
   4   3   4   2
   5   3   9   1
   6   5   6   1
   7   6   7   1
   8   6   8   1
   9   9  10   1
  10   1  11   1
  11   1  12   1
  12   1  13   1
  13   2  14   1
  14   5  15   1
  15   5  16   1
  16   6  17   1
  17   7  18   1
  18   7  19   1
  19   7  20   1
  20   8  21   1
  21   8  22   1
  22   8  23   1
  23   9  24   1
*/ 


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <math.h>
#include "globalvar.h"
#include "2DMAP.h" 
#include "molecule.h" 
#include "molprop.h" 
#include "ioLINE.h"

/** FUNCTIONS (GLOBAL) **/
int Translate_Lines_into_MOL2_Molecule();
void Write_MOL2_Molecule();
void make_multiple_conf_fname_from_single_conf_fname();

/** FUNCTIONS (LOCAL) **/





int Translate_Lines_into_MOL2_Molecule(HeadLineNode,mol)
 struct LINENODE *HeadLineNode; 
 struct MOLECULE *mol;
{
 struct LINENODE *xn; 
 char end,natom_ok,nbond_ok; 
 char status; 
 int Nline,Lline,natom,nbond,anum1,anum2,i,num_in_file;
 int Nword,Wsta[100],Wend[100]; 
 int Nword2,Wsta2[100],Wend2[100]; 
 int Nmolecule_line,Ncomment_line; 
 char *line,*buff,*buff2,*value,*key; 
 /* 
 printf("#Translate_Lines_into_MOL2_Molecule('%s')\n",mol->filename); fflush(stdout);  
 */
 
 Nline = natom = nbond = 0; 
 mol->name[0] = mol->comment[0] = '\0';
 mol->Natom = mol->Nheavyatom = 0;
 mol->Nbond = 0; 
 mol->conmap.malloced = mol->dismap.malloced = 0; 
 mol->Nmatch = 0;
 mol->chiral_flag = '0';
 mol->Npermu = 0; 
 mol->permuhead.next = NULL;
 natom_ok = nbond_ok = 0;
 Nmolecule_line = Ncomment_line = 0;

 status = ' ';
 end = 0;
 if (PAR.molnamekey =='\0') sprintf(mol->name,"%s",mol->filename);

 
 xn = HeadLineNode;
 while ((xn->next!=NULL)&&(end==0)){
   xn = xn->next;
   /* printf("%d:status '%c':'%s'\n",xn->num,status,xn->line); */
   Lline = strlen(xn->line);
   line  = (char *)malloc(sizeof(char)*(Lline+1));
   buff  = (char *)malloc(sizeof(char)*Lline);
   buff2 = (char *)malloc(sizeof(char)*Lline);
   key   = (char *)malloc(sizeof(char)*Lline);
   value = (char *)malloc(sizeof(char)*Lline);
   sprintf(line,"%s",xn->line);  

   /* printf("'%s'Natom %d/%d\n",line,natom,mol->Natom);   */
   if (strncmp(line,"@<TRIPOS>MOLECULE",17)==0){
     status = 'M'; 
     Nline = 0; 
     Nmolecule_line += 1;
     if (Nmolecule_line>1) { end = 1; status = ' ';}
   }
   if (strncmp(line,"@<TRIPOS>COMMENT",16)==0){
     status = 'C';
     Ncomment_line += 1;
     if (Ncomment_line>1) {end = 1; status = ' ';}
   }
   if (strncmp(line,"@<TRIPOS>ATOM",13)==0){status = 'A';}
   if (strncmp(line,"@<TRIPOS>BOND",13)==0){status = 'B';}
   /** (1) molecular name line ***/
/* 
ZINC15633213 
/DB/LIGAND-EXPO/SDF/BEN
conf1.mol2
*/
   /** (2) Natom and Nbond line ***/
/*
   11    10     0     0     0
 9 9 0 0 0
*/
   if ((status=='M')){
     if ((Nline==1)&&(PAR.molnamekey[0]=='\0')) sprintf(mol->name,"%s",line);

     if (Nline==2){
       Split_to_Words_With_Double_Splsym(line,' ','\t',&Nword,Wsta,Wend,100);
       if (Nword>=2){
         Get_Part_Of_Line(buff,line,Wsta[0],Wend[0]);
         mol->Natom = atoi(buff); 
         Get_Part_Of_Line(buff,line,Wsta[1],Wend[1]); 
         mol->Nbond = atoi(buff); 
         Malloc_MOLECULE(mol,mol->Natom,mol->Nbond);
         natom_ok = nbond_ok = 1;
       }
      }
   }

   /** (3) ATOM line ***/
   if ((status=='A') && (line[0]!='@') && (Lline>10) &&(natom_ok==1)){

/*
          1         2         3         4         5         6         7         8 
012345678901234567890123456789012345678901234567890123456789012345678901234567890
@<TRIPOS>ATOM
      1 C          14.9610   22.8170    4.7260 C.2     0  <1>         0.5670
      2 O          15.8360   22.6310    5.6100 O.2     0  <1>        -0.6314
      3 N          14.2950   23.9210    4.5450 N.am    0  <1>        -0.8779
      4 H          13.8110   24.0770    3.6840 H       0  <1>         0.3672
      5 H          14.2680   24.6130    5.2670 H       0  <1>         0.3672
      6 C          14.9360   21.8010    3.5270 C.2     0  <1>         0.8405
      7 O          14.0870   22.0030    2.6050 O.co2   0  <1>        -0.8163
      8 O          16.1090   21.3460    3.3700 O.co2   0  <1>        -0.8163
@<TRIPOS>ATOM
      1 H1          0.0021   -0.0041    0.0020 H         1 <0>         0.1232
      2 C1         -0.0127    1.0858    0.0080 C.3       1 <0>        -0.0495
      3 H2          1.0099    1.4631    0.0003 H         1 <0>         0.1232
      4 H3         -0.5399    1.4469   -0.8751 H         1 <0>         0.1255
@<TRIPOS>ATOM
   1 C1       -2.1450    -1.1820    -0.1090 C.ar    1   UNK       -0.40310
   2 S1       -3.0510    -0.2300    -1.2190 S.3     1   UNK        0.45590
   3 C2       -2.9150    -2.2160     0.4420 C.ar    1   UNK        0.03680
   4 C3       -0.6550    -1.0050     0.1170 C.2     1   UNK        0.38940
   5 C4       -4.4390    -1.1570    -0.9090 C.ar    1   UNK       -0.24800
   6 C5       -4.2270    -2.1890    -0.0130 C.ar    1   UNK       -0.08720
   7 N1       -0.0700     0.1120    -0.4150 N.pl3   1   UNK       -0.37930
   8 C6       -5.6930    -0.9460    -1.4820 C.ar    1   UNK       -0.10980
   9 C7       -5.2580    -3.0650     0.3400 C.ar    1   UNK       -0.05040
  10 O1        0.0610    -1.8510     0.7210 O.2     1   UNK       -0.31400
  11 N2        1.7130     2.3060     0.2500 N.4     1   UNK       -0.04860
  12 Cl1      -2.3510    -3.4000     1.5670 Cl      1   UNK        0.06460
  13 C8       -6.7310    -1.8150    -1.1280 C.ar    1   UNK       -0.01750
  14 C9       -6.5220    -2.8700    -0.2290 C.ar    1   UNK       -0.12040
  15 Cl2      -8.2930    -1.5860    -1.8150 Cl      1   UNK        0.01460
@<TRIPOS>ATOM
   1 N        52.9070    16.5460    -4.3540 N.4     1   UNK         0.2274
   2 CA       51.9980    17.6810    -4.7520 C.3     1   UNK         0.0554
   3 C        52.5700    18.7580    -5.6730 C.2     1   UNK         0.2835
   4 O        53.6330    18.7010    -6.3740 O.2     1   UNK        -0.2675
*/
      Split_to_Words_With_Double_Splsym(line,' ','\t',&Nword,Wsta,Wend,100); 
      if (Nword>5){
        Get_Part_Of_Line(buff,line,Wsta[0],Wend[0]);   num_in_file = atoi(buff);
        if (num_in_file>0){
          /* printf("#ATOM_LINE '%s'\n",line); */
          mol->atoms[natom].num         = natom;
          mol->atoms[natom].num_in_file = num_in_file;
          Get_Part_Of_Line(mol->atoms[natom].atomname,line,Wsta[1],Wsta[1]); 
          Get_Part_Of_Line(buff,line,Wsta[2],Wend[2]); mol->atoms[natom].Pos[0] = atof(buff);
          Get_Part_Of_Line(buff,line,Wsta[3],Wend[3]); mol->atoms[natom].Pos[1] = atof(buff);
          Get_Part_Of_Line(buff,line,Wsta[4],Wend[4]); mol->atoms[natom].Pos[2] = atof(buff);
          if (Nword>8) {Get_Part_Of_Line(buff,line,Wsta[8],Wend[8]); mol->atoms[natom].charge = atof(buff);}

          Get_Part_Of_Line(buff,line,Wsta[5],Wend[5]);
          Split_to_Words(buff,'.',&Nword,Wsta,Wend,100);
          Get_Part_Of_Line(mol->atoms[natom].element,buff,Wsta[0],Wend[0]);
          Change_String_ToUpper(mol->atoms[natom].element); 

          Get_Part_Of_Line(mol->atoms[natom].mol2atomtype,line,Wsta[5],Wend[5]);

          sprintf(mol->atoms[natom].resi,"MOL");
          sprintf(mol->atoms[natom].rnum,"   1 ");
          mol->atoms[natom].chain = 'A';

          mol->atoms[natom].mass_diff = 0;
          mol->atoms[natom].char_charge   = '0';
          mol->atoms[natom].stereo_parity = '0';
          sprintf(mol->atoms[natom].resi,"MOL");
          sprintf(mol->atoms[natom].rnum,"   1 ");
          mol->atoms[natom].chain = 'A';
 
          mol->atoms[natom].Nmatch = 0;
          ++natom;
          if (natom>mol->Natom){ 
            printf("#ERROR(Translate_Lines_into_MOL2_Molecule '%s'):natom %d is over the header-defined Natom %d.\n",mol->filename,natom,mol->Natom); 
            exit(1); }
         }
       }
     }
   /** (4) BOND lines ***/
   else if ((status=='B') && (line[0]!='@') && (Lline>6) &&(nbond_ok ==1)){
/*
          1         2         3         4         5         6         7         8 
012345678901234567890123456789012345678901234567890123456789012345678901234567890
@<TRIPOS>BOND
     1     1     2   ar
     2     1     6   ar
     3     1     7    1
     4     2     3   ar
     5     3     4   ar
     6     4     5   ar
     7     5     6   ar
     8     7     8    2
     9     7     9    1
@<TRIPOS>BOND
   1   1   2   1
   2   2   3   1
   3   2   5   1
   4   3   4   2
*/
    Split_to_Words_With_Double_Splsym(line,' ','\t',&Nword,Wsta,Wend,100); 
    mol->bonds[nbond].num = nbond;
    Get_Part_Of_Line(buff,line,Wsta[1],Wend[1]); 
    anum1 = atoi(buff)-1;
    Get_Part_Of_Line(buff,line,Wsta[2],Wend[2]); 
    anum2 = atoi(buff)-1;
    if ((anum1>=0) && (anum1<mol->Natom) && (anum2>=0) && (anum2<mol->Natom) ) { 
      
      mol->bonds[nbond].anum1 = anum1;
      mol->bonds[nbond].anum2 = anum2;
      Get_Part_Of_Line(buff,line,Wsta[3],Wend[3]); 
           if (strcmp(buff,"1")==0)  mol->bonds[nbond].bondtype = '1';
      else if (strcmp(buff,"2")==0)  mol->bonds[nbond].bondtype = '2';
      else if (strcmp(buff,"3")==0)  mol->bonds[nbond].bondtype = '3';
      else if (strcmp(buff,"ar")==0) mol->bonds[nbond].bondtype = 'r';
      else if (strcmp(buff,"am")==0) mol->bonds[nbond].bondtype = 'm';
      else mol->bonds[nbond].bondtype = 'x';
      mol->bonds[nbond].bondstereo = '0';
      mol->conmap.map[anum1][anum2] = mol->bonds[nbond].bondtype;
      mol->conmap.map[anum2][anum1] = mol->bonds[nbond].bondtype;
      ++nbond; 
      if (nbond > mol->Nbond){ 
        printf("#ERROR(Translate_Lines_into_MOL2_Molecule):nbond %d is over the header-defined Nbond %d.\n",nbond,mol->Nbond); 
        exit(1); }
     }
   }

   /** (5) COMMENT lines ***/
   else if ((status=='C')&&(Lline>10)){
/*
@<TRIPOS>COMMENT
    LIGANDBOX_ID = 00000001-01
    SOURCE = Namiki1010
    NAMIKI_ID = NS-00000002
    SUPPLIER = Princeton
    IDNUMBER = OSSL_184570
    MOLECULAR FORMULA = C8H5N2O2
    MOLECULAR WEIGHT = 161.14
    MOLECULAR CHARGE = -1
    NUM OF DONOR = 0
    NUM OF ACCEPTOR = 3
    HOMO = -4.638
    LUMO = 2.413
    NUM OF CHIRAL ATOMS = 0
    DELTAG = 1.5288
    ATOMIC DELTAG = 0.0899
    NOTE = Princeton_OSSL_184570;ButtPark_178\50-31;Vitas-M_STK510061;TimTec_ST5320978;Asinex_BAS-06100978;Zelinsky_UZI/2284227
*/
    Split_to_Words(line,'=',&Nword,Wsta,Wend,100); 
    if (Nword==2) {
      Get_Part_Of_Line(buff,line,Wsta[0],Wend[0]); 
      Remove_HeadTail_Space_from_String(key,buff);
      Get_Part_Of_Line(buff,line,Wsta[1],Wend[1]); 
      Remove_HeadTail_Space_from_String(value,buff);
      if (PAR.CHANGE_KEY_SPACE_TO_UNDERBAR == 'T') Change_Space_To_Underbar(key);
/*
      printf("#key '%s' PAR.molnamekey '%s'\n",key,PAR.molnamekey);
*/
      if ((PAR.molnamekey[0]!='\0')&&(strcmp(key,PAR.molnamekey)==0)){   
        sprintf(mol->name,"%s",value);
        printf("#mol->name,'%s'\n",mol->name);
      }

      if (PAR.READ_MOLECULAR_PROPERTY=='T'){
        if (PAR.CHANGE_NOTE_TO_SUPPLIERS != 'T'){ Add_key_value_string_to_KEYVALUEs(key,value,&(mol->HeadProperty)); }
        else if (PAR.CHANGE_NOTE_TO_SUPPLIERS == 'T'){
          if (strcmp(key,"SUPPLIER")==0){ sprintf(key,"SUPPLIERNAME_1");}
          if (strcmp(key,"IDNUMBER")==0){ sprintf(key,"SUPPLIERID_1");}
 
          if (strcmp(key,"NOTE")!=0){ 
            Add_key_value_string_to_KEYVALUEs(key,value,&(mol->HeadProperty));
          }
          else if (strcmp(key,"NOTE")==0){ 
            Split_to_Words(value,';',&Nword,Wsta,Wend,100); 
            printf("value '%s'\n",value);
            for (i=0;i<Nword;++i){
              Get_Part_Of_Line(buff,value,Wsta[i],Wend[i]);
              Split_to_Words(buff,'_',&Nword2,Wsta2,Wend2,100); 
              Get_Part_Of_Line(buff2,buff,Wsta2[0],Wend2[0]);
              sprintf(key,"SUPPLIERNAME_%d",i+1);
              Add_key_value_string_to_KEYVALUEs(key,buff2,&(mol->HeadProperty));
              Get_Part_Of_Line(buff2,buff,Wend2[0]+2,strlen(buff));
              sprintf(key,"SUPPLIERID_%d",i+1);
              Add_key_value_string_to_KEYVALUEs(key,buff2,&(mol->HeadProperty));
             }
          }
         }

       } /* PAR.READ_MOLECULAR_PROPERTY=='T' */

     } /* Nword == 2 */

   } /* (status=='C')&&(Lline>10) */

   Nline += 1; 
   free(key); free(value); free(buff2); free(buff); free(line);
  } /* while */

  Set_one_char_ele(mol);


 /* printf("#name '%s' Nline %d\n",mol->name,Nline); */

  if (natom!=mol->Natom){
    printf("#WARNING(mol2): Natom:%d is not consitent with number_of_atom:%d\n",mol->Natom,natom);
    mol->Natom = natom;
  }
  


 if (PAR.Wdistan>0.0){
   Malloc_FLOAT2DMAP(&(mol->dismap),mol->Natom);
   Cal_Distance_Map_for_Heavy_atoms(mol);
 }

 if (mol->Natom==0){ 
   printf("#WARNING(Translate_Lines_into_MOL2_Molecule):the file '%s' contains no atom.\n",mol->filename); 
   Set_Molform(mol);
   sprintf(mol->molform,"-");
   return(0);
 }
 /** ending procedure **/
  if (PAR.OutCalProcess=='T')
    printf("#Translate_Lines_into_MOL2_Moleclue():Natom %3d Nbond %3d '%s'\n",mol->Natom,mol->Nbond,mol->molform);

  /*
  Show_KEYVALUEs(&(mol->HeadProperty));
  */

  return(mol->Natom);

} /* end of Translate_Lines_into_MOL2_Molecule() */






void Write_MOL2_Molecule(ofname,mol,mode)
 char *ofname;
 struct MOLECULE *mol;
 char   mode;              /* 'w'rite,'a'ppend */
{
 FILE *fpo;
 int i,j;
 char str[8];
 struct KEYVALUE *kn;

 printf("#Write_MOL2_Molecule(wmode '%c')-->'%s'\n",mode,ofname);
 if (ofname[0]=='-') {fpo = stdout;}
 else{
   if (mode=='a') fpo = fopen(ofname,"a");
   else fpo = fopen(ofname,"w");
   if (fpo==NULL){
     printf("#ERROR:Can't write to '%s'\n",ofname);
     exit(1);
   }
 }

 kn = &(mol->HeadProperty);
 if (kn->next != NULL){
   fprintf(fpo,"@<TRIPOS>COMMENT\n");
   while (kn->next != NULL){
     kn = kn->next;
     fprintf(fpo," %s = %s\n",kn->key,kn->value);
   }
   fprintf(fpo,"\n");
 }

 fprintf(fpo,"@<TRIPOS>MOLECULE\n");
 fprintf(fpo,"%s\n",mol->filename);
 fprintf(fpo,"%4d%4d 0 0 0\n",mol->Natom, mol->Nbond);
 fprintf(fpo,"\n");
 fprintf(fpo,"\n");
 fprintf(fpo,"@<TRIPOS>ATOM\n");
 for (i=0;i<mol->Natom;++i){
/*
      1 C          -6.9684    0.8200    0.0000 C.3     1  LIG1        0.1046
      2 C          -8.3999    1.2681    0.0000 C.3     1  LIG1        0.1595
      3 O          -8.7276    2.7319    0.0000 O.3     1  LIG1       -0.3508
*/
    fprintf(fpo,"%7d %-2s      %10.4f%10.4f%10.4f %-5s %3d  %4s    %10.4f\n",
              mol->atoms[i].num + 1, mol->atoms[i].element, 
              mol->atoms[i].Pos[0], mol->atoms[i].Pos[1], mol->atoms[i].Pos[2],
              mol->atoms[i].mol2atomtype, 1, mol->atoms[i].resi, mol->atoms[i].charge);

 }
/*
          1         2         3         4         5         6         7         8 
012345678901234567890123456789012345678901234567890123456789012345678901234567890
@<TRIPOS>BOND
     1     1     2   ar
     2     1     6   ar
     3     1     7    1
*/
 fprintf(fpo,"@<TRIPOS>BOND\n");
 for (j=0;j<mol->Nbond;++j){
        if (mol->bonds[j].bondtype=='r') sprintf(str,"ar");
   else if (mol->bonds[j].bondtype=='m') sprintf(str,"am");
   else if (mol->bonds[j].bondtype=='1') sprintf(str,"1");
   else if (mol->bonds[j].bondtype=='2') sprintf(str,"2");
   else if (mol->bonds[j].bondtype=='3') sprintf(str,"3");
   else  sprintf(str,"x");
   fprintf(fpo,"%6d%6d%6d   %2s\n",
        j+1,mol->bonds[j].anum1+1,mol->bonds[j].anum2+1,str);
 }

 if (ofname[0]!='-'){fclose(fpo);}

} /* end of Write_MOL2_Molecule() */



void make_multiple_conf_fname_from_single_conf_fname(new_filename,orig_filename,conf_number,all_conf_number)
  char *new_filename;
  char *orig_filename;
  int  conf_number;
  int  all_conf_number;
{
/*
 >> EXAMPLE <<
  orig_filename[] = "1fin.ATP.pdb" conf_number = 2  all_conf_number=5 ==> new_filename[] = "1fin.ATP_2.mol2"
  orig_filename[] = "IRE.mol2" conf_number = 4 all_conf_number=10 ==> new_filename[] = "IRE_04.mol2"
  orig_filename[] = "ATPpdb" conf_number = 7  ==> new_filename[] = "ATPpdb_7"
   
 */ 
  int Nword,Wsta[10],Wend[10],keta,diff_keta,i;
  char filehead[1024],filetail[1024],numstr[100],numstr_orig[100]; 

  Split_to_Words(orig_filename,'.',&Nword,Wsta,Wend,10);
  if (Nword==1){
    sprintf(new_filename,"%s_%d",orig_filename,conf_number);
  }
  else{
    Get_Part_Of_Line(filetail,orig_filename,Wsta[Nword-1],Wend[Nword-1]); 
    Get_Part_Of_Line(filehead,orig_filename,0,Wsta[Nword-1]-2); 
    keta = (int)ceil(log((double)(all_conf_number+1.0))/log(10.0));
    /* printf("#conf_number %d all_conf_number %d keta %d strlen(numstr):%d\n",conf_number,all_conf_number,keta,strlen(numstr)); */
    sprintf(numstr,"%d",conf_number);
    if (strlen(numstr)<keta){
      diff_keta = keta-strlen(numstr);
      /* printf("#diff_keta %d\n",diff_keta); */
      for (i=0;i<diff_keta;++i){numstr[i] = '0';}
      numstr[diff_keta] = '\0';
      sprintf(numstr_orig,"%d",conf_number);
      strcat(numstr,numstr_orig);
    }
    sprintf(new_filename,"%s_%s.%s",filehead,numstr,filetail);
  }
  /* printf("#orig '%s' conf_number %d --> new '%s'\n",orig_filename,conf_number,new_filename); */
} /* end of make_multiple_conf_fname_from_single_conf_fname() */

