/*
 
 <ioPDB.c> 
 
  input/output functions for PDB files

==============================================================================
Copyright 2018  Takeshi Kawabata.  All rights reserved.

This software is released under the three-clause BSD License, see LICENSE.txt.
==============================================================================



  * 2016/11/14.  A bug was found in "Translate_Lines_into_PDB_Molecule()".
 
   Lline (length of ln->line) is that of the previous line.
   Therefore, if a ATOM/HETATM line is on the head of the file,
    THE FIRST ATOM CAN BE MISSED !!

   Fortunately,  if "HEADER" or "REMARK" lines with more than 53 characters,
   exist before ATOM/HETATM line, there is no problem to read the atoms.
  
 
 >> old source with the bug <<
 (2) Read PDB file 
 ln = HeadLineNode;
 mol->Natom = mol->Nbond = 0;
 natom = 0;
 while ((ln->next != NULL)&&(end==0)){
   ln = ln->next;
   Lline = strlen(line);
   sprintf(line,"%s",ln->line);

 >> new correced source  <<
 (2) Read lines of PDB file 
 ln = HeadLineNode;
 mol->Natom = mol->Nbond = 0;
 natom = 0;
 while ((ln->next != NULL)&&(end==0)){
   ln = ln->next;
   sprintf(line,"%s",ln->line);

COMPND    994
AUTHOR    GENERATED BY OPEN BABEL 2.2.0
ATOM      1  O   PHE A   1       0.490   0.018  -0.676  1.00  0.00           O
ATOM      2  OXT PHE A   1      -1.527   0.616  -1.640  1.00  0.00           O
ATOM      3  N   PHE A   1      -1.896   2.780  -0.505  1.00  0.00           N
ATOM      4  CB  PHE A   1      -0.772   1.651   1.435  1.00  0.00           C
ATOM      5  CA  PHE A   1      -0.650   2.034  -0.040  1.00  0.00           C
ATOM      6  CG  PHE A   1      -1.004   2.844   2.338  1.00  0.00           C
ATOM      7  CD1 PHE A   1      -2.202   2.971   3.055  1.00  0.00           C
ATOM      8  CD2 PHE A   1      -0.023   3.837   2.471  1.00  0.00           C
ATOM      9  C   PHE A   1      -0.520   0.725  -0.863  1.00  0.00           C
ATOM     10  CE1 PHE A   1      -2.422   4.081   3.871  1.00  0.00           C
ATOM     11  CE2 PHE A   1      -0.246   4.946   3.288  1.00  0.00           C
ATOM     12  CZ  PHE A   1      -1.446   5.070   3.985  1.00  0.00           C
ATOM     13  H 1 PHE A   1      -2.325   2.059  -1.140  1.00  0.00           H
ATOM     14  H 2 PHE A   1      -1.667   3.576  -1.100  1.00  0.00           H
ATOM     15  H 3 PHE A   1      -2.560   3.010   0.234  1.00  0.00           H
ATOM     16  HB1 PHE A   1       0.140   1.142   1.774  1.00  0.00           H
ATOM     17  HB2 PHE A   1      -1.583   0.922   1.568  1.00  0.00           H
ATOM     18  HA  PHE A   1       0.196   2.699  -0.240  1.00  0.00           H
ATOM     19  HD1 PHE A   1      -2.968   2.200   3.000  1.00  0.00           H
ATOM     20  HD2 PHE A   1       0.932   3.747   1.956  1.00  0.00           H
ATOM     21  HE1 PHE A   1      -3.348   4.169   4.434  1.00  0.00           H
ATOM     22  HE2 PHE A   1       0.524   5.706   3.394  1.00  0.00           H
ATOM     23  HZ  PHE A   1      -1.613   5.928   4.631  1.00  0.00           H
HETATM 2442  C6  IRE A2020     -51.681   1.085 -22.378  1.00 89.23           C
HETATM 2443  NAS IRE A2020     -50.876   0.406 -23.183  1.00 89.31           N
HETATM 2444  CAY IRE A2020     -50.978   0.472 -24.509  1.00 89.06           C
HETATM 2445  CAG IRE A2020     -50.925   1.714 -25.133  1.00 89.22           C
HETATM 2446  CAX IRE A2020     -51.007   1.806 -26.512  1.00 89.05           C
HETATM 2447 CL   IRE A2020     -50.943   3.360 -27.240  1.00 89.85          CL
HETATM 2448  CAW IRE A2020     -51.141   0.667 -27.293  1.00 89.10           C
HETATM 2449  FAB IRE A2020     -51.218   0.793 -28.634  1.00 88.75           F
HETATM 2450  CAD IRE A2020     -51.189  -0.585 -26.674  1.00 89.45           C
HETATM 2451  CAE IRE A2020     -51.103  -0.682 -25.280  1.00 89.23           C
HETATM 1452 CU    CU A 100      -8.925   3.189   2.681  1.00  0.00          CU  
HETATM 1742 MG    MG A 225     -29.829 -15.972  22.007  1.00 19.29          MG
HETATM 1743  S   SO4 A 226     -27.597 -15.438  34.705  1.00 25.67           S
HETATM 1744  O1  SO4 A 226     -27.176 -15.003  36.008  1.00 20.42           O
HETATM 1745  O2  SO4 A 226     -29.045 -15.681  34.578  1.00 29.62           O
HETATM 1746  O3  SO4 A 226     -26.990 -16.717  34.290  1.00 24.66           O
HETATM 1747  O4  SO4 A 226     -27.308 -14.322  33.737  1.00 21.80           O
012345678901234567890123456789012345678901234567890123456789012345678901234567890
          1         2         3         4         5         6         7         8  
CONECT    1    9
CONECT    2    9
CONECT    3    5   13   14   15
CONECT    3
CONECT    4    5    6   16   17
CONECT    4
CONECT    5    3    4    9   18
CONECT    5
CONECT    6    4    7    8
CONECT    7    6   10   19
CONECT    8    6   11   20
CONECT    9    1    2    5
CONECT   10    7   12   21
CONECT   11    8   12   22
CONECT   12   10   11   23
CONECT   13    3
CONECT   14    3
CONECT   15    3
CONECT   16    4
CONECT   17    4
CONECT   18    5
CONECT   19    7 
CONECT   20    8
CONECT   21   10
CONECT   22   11
CONECT   23   12
MASTER        0    0    0    0    0    0    0    0   23    0   23    0
END

*/ 


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string.h>
#include <math.h>
#include <ctype.h>
#include "globalvar.h"
#include "2DMAP.h" 
#include "molecule.h" 
#include "ioSDF.h" 
#include "match.h" 
#include "qRMS.h" 
#include "molprop.h" 
#include "vector3.h" 
#include "options.h" 

/** FUNCTIONS (GLOBAL) **/
int  Translate_Lines_into_PDB_Molecule();
void Write_PDB_Molecule();
void Guess_Bonds_from_Atom_XYZ();
void Guess_Orbital_from_Atom_XYZ();
void Set_Aromatic_Ring_by_3D_Planarity();
void Set_DAMRL_from_3D_structure();
void Set_DAMRL_from_3D_RING();
void Set_Resi_Chain_Rnum_to_Molecule();
void Set_Unique_atomname_to_Molecule();

/** FUNCTIONS (LOCAL) **/
static int atom_num_FROM_atom_num_in_file();
static float Angle_bwn_Vec();
static void Element_from_PDB_Atomname();
static void CONECT_line_into_ConnectAtomNum();






int Translate_Lines_into_PDB_Molecule(HeadLineNode,mol,AtmHetType,BondType)
  struct LINENODE *HeadLineNode;
  struct MOLECULE *mol;
  char   AtmHetType; /* 'A'tom, 'H'etatm, 'B'oth */
  char   BondType;    /* 'B': guess bonds by distances and cal topo-distances */
{
 struct LINENODE *ln;
 char line[MAX_LENGTH_LINE];
 char end,B[128],atmhet,chainID,resi[4];
 int i,Nline,Lline,natom,nbond_malloc;
 int con_atom_num_in_file[10],con_atom_num[10],Ncon_atom;

/*
 printf("#Translate_Lines_into_PDB_Molecule(AtmHetType:%c BondType:%c mol->chain '%c')\n",
      AtmHetType,BondType,mol->chain);
 */
 /** (0) Initialize **/
 end = 0;
 Nline = natom = nbond_malloc = 0; 
 mol->name[0] = '\0';
 sprintf(mol->name,"%s",mol->filename); 
 mol->Natom = mol->Nheavyatom = 0;
 mol->conmap.malloced = mol->dismap.malloced = 0; 
 mol->Nmatch = 0;
 mol->chiral_flag = '0';
 mol->Npermu = 0;
 mol->permuhead.next = NULL;
 
 /*** (1) Read PDB file only to know Number of atoms ***/
 ln = HeadLineNode; 
 natom = nbond_malloc = Lline = 0;
 while ((ln->next != NULL)&&(end==0)){
   ln = ln->next;
   sprintf(line,"%s",ln->line);
   /* printf("#'%s'\n",ln->line); */
   Lline = strlen(ln->line);
   atmhet = '-';
   chainID = resi[0] = '\0'; 
   if (strncmp(line,"ATOM  ",6)==0) atmhet = 'A';
   if (strncmp(line,"HETATM",6)==0) atmhet = 'H';
   if (atmhet!='-'){
     chainID = line[21];
     Get_Part_Of_Line(resi,line,17,19);
   }
   if ( ((atmhet==AtmHetType) || ((AtmHetType=='B') && (atmhet!='-'))) 
         && ((mol->chain=='-')||(mol->chain==chainID)) 
         && ((mol->resi[0]=='\0')||(strcmp(mol->resi,resi)==0))){ ++natom;}

   if ((strncmp(line,"CONECT",6)==0) && (Lline>10)&&(line[10]!=' ')){
     Ncon_atom = 0;
     CONECT_line_into_ConnectAtomNum(line,&Ncon_atom,con_atom_num_in_file);
     nbond_malloc += Ncon_atom;
    }
 }

 /* printf("#natom %d nbond_malloc %d\n",natom,nbond_malloc); */
 
 Malloc_MOLECULE(mol,natom,nbond_malloc);
 
 /*** (2) Read lines of PDB file ***/
 ln = HeadLineNode; 
 mol->Natom = mol->Nbond = 0; 
 natom = 0;
 while ((ln->next != NULL)&&(end==0)){
   ln = ln->next;
   sprintf(line,"%s",ln->line);
   Lline = strlen(ln->line);
   /* printf("#'%s':Lline %d\n",ln->line,Lline); */
   
   /** 'ATOM' or 'HETATM' lines **/
   atmhet = '-';
   chainID = resi[0] = '\0'; 

   if (strncmp(line,"ATOM  ",6)==0) atmhet = 'A';
   if (strncmp(line,"HETATM",6)==0) atmhet = 'H';

   if (atmhet!='-'){ 
     chainID = line[21];
     Get_Part_Of_Line(resi,line,17,19);
   }
   /*
   printf("#atmhet %c AtmHetType %c Lline %d chain '%c' ChainID '%c'\n",atmhet,AtmHetType,Lline,mol->chain,chainID);
   */

   if ( ((atmhet==AtmHetType) || ((AtmHetType=='B') && (atmhet!='-'))) 
         && (Lline>53)
         && ((mol->chain=='-')||(mol->chain==chainID)) 
         && ((mol->resi[0]=='\0')||(strcmp(mol->resi,resi)==0)) ){

     /* printf("#Try to include the line '%s'\n",ln->line); */
     mol->atoms[natom].num = natom;
     mol->atoms[natom].atmhet  = atmhet;
     Get_Part_Of_Line(B,line,6,10);  mol->atoms[natom].num_in_file = atoi(B);
     Get_Part_Of_Line(B,line,30,37); mol->atoms[natom].Pos[0] = atof(B);
     Get_Part_Of_Line(B,line,38,45); mol->atoms[natom].Pos[1] = atof(B);
     Get_Part_Of_Line(B,line,46,53); mol->atoms[natom].Pos[2] = atof(B);
     Get_Part_Of_Line(mol->atoms[natom].atomname,line,12,15);
     Change_String_ToUpper(mol->atoms[natom].atomname);
     Get_Part_Of_Line(mol->atoms[natom].resi,line,17,19);
     Get_Part_Of_Line(mol->atoms[natom].rnum,line,22,26);
     mol->atoms[natom].chain = line[21];
     if (Lline>64){
       Get_Part_Of_Line(B,line,60,65); mol->atoms[natom].tFactor = atof(B);
     }
     else mol->atoms[natom].tFactor = -1.0;

     mol->atoms[natom].orbital = '-';
     mol->atoms[natom].DAMRL   = '-';
/*    
012345678901234567890123456789012345678901234567890123456789012345678901234567890
          1         2         3         4         5         6         7         8  
HETATM 2225 BR1  HMD A 400      23.120  26.871  28.136  1.00 63.13          BR  
HETATM 2226  O1  HMD A 400      25.184  31.320  30.286  1.00 45.50           O  
HETATM 2227  O2  HMD A 400      30.537  29.959  25.467  1.00 43.12           O  
HETATM 2228  N1  HMD A 400      24.542  29.157  28.792  1.00 48.35           N  
HETATM 5274  C4  GCP A1749      14.439  21.481  -2.931  1.00  7.13           C  
HETATM 5275 MG    MG A1750      10.612  12.184  -8.148  1.00  5.01          MG  
HETATM 5276  PG  GCP D1749      21.687  11.358  17.910  1.00 11.10           P  
HETATM 5277  O1G GCP D1749      20.774  10.642  16.983  1.00  7.76           O  
HETATM 5278  O2G GCP D1749      21.638  11.013  19.350  1.00 14.21           O  
HETATM 5279  O3G GCP D1749      23.127  11.469  17.544  1.00 11.34           O  
HETATM 5280  C3B GCP D1749      21.121  13.108  17.927  1.00  9.79           C  
HETATM 5281  PB  GCP D1749      19.444  13.422  18.583  1.00  8.41           P  
HETATM 2050  FE  670 A   1      20.305  11.132  13.458  1.00  0.00  B   300 FE
HETATM 2051  NAA 670 A   1      17.394   8.763  12.431  1.00  0.00  B   300  N
HETATM 2052  NAB 670 A   1      16.774   7.874  13.019  1.00  0.00  B   300  N

*/
     Get_Part_Of_Line(B,line,76,77);
     if ((B[0]==' ')&&(B[1]!=' ')){ B[0] = B[1]; B[1] = '\0'; }
     if (Check_Element_String_Or_Not(B)==1){
       sprintf(mol->atoms[natom].element,"%s",B);
       /* printf("#from_end_of_line '%s'\n",mol->atoms[natom].element); */
     }
     else{
       Element_from_PDB_Atomname(mol->atoms[natom].element,mol->atoms[natom].atomname);
       /* printf("#from_atom_name '%s'\n",mol->atoms[natom].element); */
     }
     sprintf(mol->atoms[natom].mol2atomtype,"%s",mol->atoms[natom].element);

     mol->atoms[natom].mass_diff = 0;
     mol->atoms[natom].char_charge = '0';
     mol->atoms[natom].stereo_parity = '0';
     mol->atoms[natom].charge = 0.0;

     ++natom;  
     mol->Natom = natom;
   } /* for ATOM and HETATM LINE */
 
     /*
     Get_Part_Of_Line(an->Resi,line,17,19);
     Get_Part_Of_Line(an->Rnum,line,22,26);
     */

     /** 'CONECT' lines **/
   if ((strncmp(line,"CONECT",6)==0)&&(BondType=='B')){
/*
012345678901234567890123456789012345678901234567890
          1         2         3         4          
CONECT    1    9
CONECT    2    9
CONECT    3    5   13   14   15
CONECT    1    2    3    4    8'
*/
       Ncon_atom = 0;
       CONECT_line_into_ConnectAtomNum(line,&Ncon_atom,con_atom_num_in_file);
       for (i=0;i<Ncon_atom;++i){
         con_atom_num[i] = atom_num_FROM_atom_num_in_file(mol,con_atom_num_in_file[i]);
         /* printf("#con_atom_num_in_file %d con_atom_num %d\n",con_atom_num_in_file[i],con_atom_num[i]); */
       }

       for (i=1;i<Ncon_atom;++i){
         if ((con_atom_num[0]>=0) && (con_atom_num[i]>=0)){

            mol->conmap.map[con_atom_num[0]][con_atom_num[i]] = '1';
            mol->conmap.map[con_atom_num[i]][con_atom_num[0]] = '1';

            if (mol->Nbond < nbond_malloc){
              mol->bonds[mol->Nbond].num = mol->Nbond;
              mol->bonds[mol->Nbond].anum1 = con_atom_num[0];
              mol->bonds[mol->Nbond].anum2 = con_atom_num[i];
              mol->bonds[mol->Nbond].bondtype   = '1';
              mol->bonds[mol->Nbond].bondstereo = '0';
/*
              printf("#BOND %d anum1 %d anum2 %d bondtype '%c' bondstereo '%c' %d %d\n",
               mol->bonds[mol->Nbond].num, mol->bonds[mol->Nbond].anum1, mol->bonds[mol->Nbond].anum2, 
               mol->bonds[mol->Nbond].bondtype, mol->bonds[mol->Nbond].bondstereo,con_atom_num[0],con_atom_num[i]);
 */
              mol->Nbond += 1;
            }
        }
      }
   } /* CONNECT LINE */



   Nline += 1; 
 } /* while ((ln->next != NULL)&&(end==0)) */



/*
 printf("#Nheavyatom %d\n",mol->Nheavyatom);
  printf("#Read_PDB_Moleclue('%s'):Natom %3d Nheavy %3d Nbond %3d\n",mol->filename,mol->Natom,mol->Nheavyatom,mol->Nbond);
 */

  return(mol->Natom);
} /* end of Translate_Lines_into_PDB_Molecule() */










void Write_PDB_Molecule(ofname,mol,mode,ChainID,model_num,start_atom_num,DAMRLout,PROPERTYout,comment)
  char  *ofname;        /* if ofname=='-', of = stdout */
  struct MOLECULE *mol;
  char mode;            /* 'w'rite,'a'ppend */
  char ChainID;         /* ChainID for output. '-':use original ChainID */
  int  model_num;       /* number of MODEL. if (<0), not output "MODEL" and "ENDMDL" lines */
  int  start_atom_num;  /* start_atom_num when renumbering. if (<0), use the original atom number. */
  char DAMRLout;        /* 'D':output with DAMRL atomname*/
  char PROPERTYout;     /* 'P':output atom properties, such as EC  */
  char *comment;
{
 int i,j,Nbond,nC,nN,nO,nX,L;
 FILE *fpo;
 char atom_str[6],chain,buff[128];
 int Wsta[100],Wend[100],Nword;



 /** [0] Renumbering atom_num into subnum **/
 if (start_atom_num > 0){
   mol->atoms[0].subnum = start_atom_num;
   for (i=1;i<mol->Natom;++i){ mol->atoms[i].subnum = mol->atoms[i-1].subnum + 1;}
 }
 else{
   for (i=0;i<mol->Natom;++i){ mol->atoms[i].subnum = mol->atoms[i].num_in_file;}
 }

 if (mol->resi[0] != '\0'){
   for (i=0;i<mol->Natom;++i){
     sprintf(mol->atoms[i].resi,"%s",mol->resi);
   }
 } 

 /*** [1] Write the molecule in PDB format ***/
 if (ofname[0]=='-'){
   fpo = stdout;
 }
 else{
   if (mode=='w'){
     printf("#Write_PDB_Molecule(mode '%c' ChainID:%c model_num %d start_atom_num %d DAMRLout %c)-->'%s'\n",mode,ChainID,model_num,start_atom_num,DAMRLout,ofname);
   }
   if (mode=='a') fpo = fopen(ofname,"a");
   else           fpo = fopen(ofname,"w");
   if (fpo==NULL){
     printf("#ERROR:Can't write to '%s'\n",ofname);
     exit(1);
   }
 }
 
 fprintf(fpo,"REMARK name_of_molecule '%s'\n",mol->name); 
 fprintf(fpo,"REMARK output_filename '%s'\n",ofname);
 fprintf(fpo,"REMARK Natom %4d Nbond %4d\n",mol->Natom,mol->Nbond); 
 fprintf(fpo,"REMARK COMMAND \"%s\"\n",PAR.COMMAND); 
 Set_END_DATE();
 fprintf(fpo,"REMARK DATE_START    %s\n",PAR.START_DATE);
 fprintf(fpo,"REMARK DATE_END      %s\n",PAR.END_DATE);
 fprintf(fpo,"REMARK LAST_MOD_DATE %s\n",LAST_MOD_DATE);
 fprintf(fpo,"REMARK COMP_TIME  %lf seconds\n",PAR.COMP_TIME_SEC);
 fprintf(fpo,"REMARK HOSTNAME   %s\n",string_getenv("HOSTNAME"));
 fprintf(fpo,"REMARK WEatommatch %f\n",PAR.WEatommatch);
 fprintf(fpo,"REMARK WEvolmovlap %f\n",PAR.WEvolmovlap);
 fprintf(fpo,"REMARK WEprotclash %f\n",PAR.WEprotclash);
 fprintf(fpo,"REMARK WEprotatrct %f\n",PAR.WEprotatrct);
 fprintf(fpo,"REMARK WEselfclash %f\n",PAR.WEselfclash);
 fprintf(fpo,"REMARK WEtpdisrest %f\n",PAR.WEtpdisrest);
 if (DAMRLout=='D'){
   /* fprintf(fpo,"REMARK   Atomname is [element] + [DAMRL] + [nC or nN or nO or nX]\n"); */
   fprintf(fpo,"REMARK   'DAMRL' is assigned as ChainID.\n");
   fprintf(fpo,"REMARK   (D:donor, A:acceptor, M:mixed donor and acceptor, R:aromatic, L:aliphatic.)\n");
   fprintf(fpo,"REMARK   Method of 'DAMRLassign' :%c\n",PAR.DAMRLassign);
 }
 if (comment[0]!='\0'){
   /* Split_to_Words(comment,' ',&Nword,Wsta,Wend,100); */
   Split_to_Words_With_Double_Splsym(comment,' ','\n',&Nword,Wsta,Wend,100);
   fprintf(fpo,"REMARK COMMENT:");
   j = 0;
   for (i=0;i<Nword;++i){
     Get_Part_Of_Line(buff,comment,Wsta[i],Wend[i]);
     L = strlen(buff);
     if ((j+L+1)>65){
       fprintf(fpo,"\nREMARK COMMENT:");
       j = 0; 
     }
     fprintf(fpo," %s",buff);
     j += (L+1);
   }
   fprintf(fpo,"\n");
 }
 if (model_num>0) fprintf(fpo,"MODEL    %5d\n",model_num);
 if (PROPERTYout=='P'){
   fprintf(fpo,"REMARK                                                              ele orbi ring DAMRL\n");
   fprintf(fpo,"REMARK                                                                     nei# C N O S P H EC0 EC1 EC2 EC3 EC4\n");
 }

/*
** 80 characters in one line **
          1         2         3         4         5         6         7
01234567890123456789012345678901234567890123456789012345678901234567890123456789
ATOM      1  N   MET A   1     -14.516 190.105 102.118  1.00 59.35           N  
ATOM      2  CA  MET A   1     -13.352 190.614 102.876  1.00 59.50           C
ATOM      3  C   MET A   1     -11.938 190.404 102.228  1.00 59.92           C
ATOM      4  O   MET A   1     -10.953 191.043 102.629  1.00 57.60           O
*/


 nC = nO = nN = nX = 0;
 for (i=0;i<mol->Natom;++i){
    if (mol->atoms[i].atmhet=='A'){ fprintf(fpo,"ATOM  "); }
                          else    { fprintf(fpo,"HETATM"); }
    if (ChainID=='-') { chain = mol->atoms[i].chain; }
                 else { chain = ChainID;}

    if (DAMRLout=='D'){
      chain = mol->atoms[i].DAMRL;
    }

         if (strcmp(mol->atoms[i].element,"C")==0) { nC += 1;}
    else if (strcmp(mol->atoms[i].element,"N")==0) { nN += 1;}
    else if (strcmp(mol->atoms[i].element,"O")==0) { nO += 1;}
    else {  nX += 1;}

/*
    if (DAMRLout=='D'){ 
      sprintf(atom_str,"%2s%c%c",mol->atoms[i].element,mol->atoms[i].DAMRL,abc);
      tFactor = 1.0;
    }
    else{ 
      sprintf(atom_str,"%s",mol->atoms[i].atomname);
    }
*/
    sprintf(atom_str,"%s",mol->atoms[i].atomname);

/* 
    fprintf(fpo,"%5d %4s %3s %c%5s   %8.3f%8.3f%8.3f%6.2f%6.2f          %2s",
        mol->atoms[i].subnum,atom_str,mol->atoms[i].resi,chain,mol->atoms[i].rnum,
        mol->atoms[i].Pos[0], mol->atoms[i].Pos[1],mol->atoms[i].Pos[2],0.0,mol->atoms[i].tFactor,mol->atoms[i].element);
*/

    fprintf(fpo,"%5d %4s%4s %c%5s   %8.3f%8.3f%8.3f%6.2f%6.2f          %2s",
        mol->atoms[i].subnum,atom_str,mol->atoms[i].resi,chain,mol->atoms[i].rnum,
        mol->atoms[i].Pos[0], mol->atoms[i].Pos[1],mol->atoms[i].Pos[2],0.0,mol->atoms[i].tFactor,mol->atoms[i].element);

/* ATOM      8  CD2 PHE A   1      -0.023   3.837   2.471  1.00  0.00           C*/
/* HETATM 2340 MG    MG A 382      -2.100  27.334  13.797  0.60 15.46          MG*/
/* ATOM    141  HD3 ARG A   9      -4.643 -10.237   4.725  1.00  0.00           H*/
/* ATOM    142  HE  ARG A   9      -5.682  -9.600   2.181  1.00  0.00           H*/
/* ATOM    143 HH11 ARG A   9      -2.852  -9.196   4.079  1.00  0.00           H*/
/* ATOM    144 HH12 ARG A   9      -1.767  -9.204   2.731  1.00  0.00           H*/

/*                                                                   0123456789  */
  /*
     fprintf(fpo," %3s",mol->atoms[i].atomtype);
  */

    if (PROPERTYout=='P'){
      fprintf(fpo," %3s %2s %c %c %c %d %d %d %d %d %d %3d %3d %3d %3d %3d",
          mol->atoms[i].atomtype,mol->atoms[i].element,
          mol->atoms[i].orbital,mol->atoms[i].ring, mol->atoms[i].DAMRL,
          mol->atoms[i].NneiC, mol->atoms[i].NneiN, mol->atoms[i].NneiO, mol->atoms[i].NneiS, mol->atoms[i].NneiP,
          mol->atoms[i].NneiH, mol->atoms[i].EC0, mol->atoms[i].EC1, mol->atoms[i].EC2,mol->atoms[i].EC3, mol->atoms[i].EC4);
    }

    fprintf(fpo,"\n");
  }

 if (mol->conmap.malloced==1){
/*
   for (i=0;i<mol->Natom;++i){
     Nbond = 0; 
     for (j=i+1;j<mol->Natom;++j){ if (mol->conmap.map[i][j]!='0') ++Nbond; } 
     if (Nbond>0){
      fprintf(fpo,"CONECT%5d",mol->atoms[i].subnum);
      for (j=i+1;j<mol->Natom;++j) { 
        if (mol->conmap.map[i][j]!='0') fprintf(fpo,"%5d",mol->atoms[j].subnum);
       }
      fprintf(fpo,"\n");
     }
   }
*/
   for (i=0;i<mol->Natom;++i){
     Nbond = 0; 
     for (j=0;j<mol->Natom;++j){ if ((i!=j)&&(mol->conmap.map[i][j]!='0')) ++Nbond; } 
     if (Nbond>0){
      fprintf(fpo,"CONECT%5d",mol->atoms[i].subnum);
      for (j=0;j<mol->Natom;++j) { 
        if ((i!=j)&&(mol->conmap.map[i][j]!='0')) fprintf(fpo,"%5d",mol->atoms[j].subnum);
       }
      fprintf(fpo,"\n");
     }
   }

 }
 fprintf(fpo,"TER\n");
 if (model_num>0) fprintf(fpo,"ENDMDL\n");

 if (ofname[0]!='-'){fclose(fpo);}

} /* end of Write_PDB_Molecule() */





void Guess_Bonds_from_Atom_XYZ(mol)
 struct MOLECULE *mol;
{
/*
  NOTE: following three functions have to be peformed before Guess_Bonds_from_Atom_XYZ() !!:
    1) Set_one_char_ele(mol);
    2) Malloc_FLOAT2DMAP(&(mol->dismap),mol->Natom);
    3) Cal_Distance_Map(mol);
 */

 /*
 <Typical Bond Length>

 aromatic C-C : 1.40 A
 sp3      C-C : 1.50--1.68 A
          C-O : 1.18--1.59 A
          S-C : 1.54--1.82 A
          S-S : 2.00--2.26 A
          P-O : 1.56--1.76 A
          N-O : 1.22A -- 1.38 A     (NTI,NFZ)
aromtic  N-C : 1.34--1.36 A
        C-O-C : 1.45 A
          C=O : 1.24 A
        C-S-C : 1.80 A
          S-C : 1.80 A
        O-P-O : 1.77 A
 hydrogens C-H: 1.09 A
           C-O: 0.96 A

 others:
        I-C   : 2.31 A
        F-C   : 1.19 A
        F-C   : 0.97 A
        RU-C  : 2.29 A
        CU-O  : 1.56 A

 Therefore, we set normally, Dbond_min = 1.1 A, Dbond_max = 1.9 A.
 If one of the atoms are not 'C','N','O','S','P',
   Dbond_min = 0.9 A, Dbond_max = 2.4 A.

*/
 int Nbond_max[256];
 char atm_standard[256];
 int a,b,c,hit,min_a,min_b,n, Nround;
 float minD,Dvdw,Dmin_bond,Dmax_bond;
 char ele_a,ele_b;
 
 printf("#Guess_Bonds_from_Atom_XYZ('%s')\n",mol->filename);

 /** [1] Initialize **/ 
 for (c=0;c<256;++c) { Nbond_max[c] = 4; atm_standard[c] = 0;} 
 Nbond_max['C'] = 4; atm_standard['C'] = 1;
 Nbond_max['O'] = 2; atm_standard['O'] = 1;
 Nbond_max['N'] = 4; atm_standard['N'] = 1;
 Nbond_max['S'] = 4; atm_standard['S'] = 0;
 Nbond_max['P'] = 4; atm_standard['P'] = 1;
 Nbond_max['F'] = 1; 
 Nbond_max['c'] = 1; 
 Nbond_max['b'] = 1; 
 Nbond_max['I'] = 1; 
 Nbond_max['H'] = 1; 
 Nbond_max['f'] = 10;  /* Fe */
 Nbond_max['u'] = 10;  /* Cu */
 Nbond_max['R'] = 10;  /* Ru */
 Nbond_max['r'] = 10;  /* Re */

 if (mol->conmap.malloced==0){Malloc_CHAR2DMAP(&(mol->conmap),mol->Natom); }
 if (mol->dismap.malloced==0){Malloc_FLOAT2DMAP(&(mol->dismap),mol->Natom);} 
 /* 
 Cal_Distance_Map_for_Heavy_atoms(mol);
 */
 Cal_Distance_Map(mol);
 mol->Nbond = 0;
 for (a=0;a<mol->Natom;++a){
   mol->atoms[a].Nnei_heavy = mol->atoms[a].Nneighbor = 0;
   for (b=a+1;b<mol->Natom;++b){ mol->conmap.map[a][b] = '0';}
 }

 /** [2] Assign bond for the atom pair with the minimum distance for heavy atom **/ 
 min_a = min_b = 0;
 Dvdw = 0.0; 
 Nround = 0;
 do{
  Nround += 1;
  hit = 0;
  minD = -1.0;
  for (a=0;a<mol->Natom;++a){
    ele_a = mol->atoms[a].one_char_ele;
    if (ele_a != 'H'){
      for (b=a+1;b<mol->Natom;++b){
        ele_b = mol->atoms[b].one_char_ele;
        if (ele_b != 'H'){
          if ((mol->conmap.map[a][b]=='0') && 
              (mol->atoms[a].Nnei_heavy < Nbond_max[(int)ele_a]) &&
              (mol->atoms[b].Nnei_heavy < Nbond_max[(int)ele_b])  ){
            Dvdw = mol->dismap.map[a][b];
                  if ((ele_a=='S') && (ele_b=='S')) { Dmin_bond = 1.10; Dmax_bond = 2.40;} 
             else if ((ele_a=='S') || (ele_b=='S')) { Dmin_bond = 1.10; Dmax_bond = 1.95;} 
             else if ((ele_a=='N') && (ele_b=='O')) { Dmin_bond = 1.10; Dmax_bond = 1.50;} 
             else if ((ele_a=='O') && (ele_b=='N')) { Dmin_bond = 1.10; Dmax_bond = 1.50;} 
             else if ((atm_standard[(int)ele_a]==0) || (atm_standard[(int)ele_b]==0)){ Dmin_bond = 0.90; Dmax_bond = 2.40;} 
                                              else  { Dmin_bond = 1.10; Dmax_bond = 1.95;}
 /*  
           printf("round %d: A %d ele '%c' '%s' -- B %d ele '%c' '%s' Dvdw %f Dmin_bond %f Dmax_bond %f\n",
              Nround,
              mol->atoms[a].num_in_file, ele_a, mol->atoms[a].atomname,
              mol->atoms[b].num_in_file, ele_b, mol->atoms[b].atomname,mol->dismap.map[a][b],Dmin_bond,Dmax_bond);
 */
            if ((Dmin_bond<Dvdw) && (Dvdw<Dmax_bond) && ((hit==0) || (Dvdw<minD))) {
               minD = mol->dismap.map[a][b]; min_a = a; min_b = b; hit = 1; 
            }
         } 
       }
     } 
   }
  } 
  if (hit==1){
/*
    printf("%s Nround %d ACCEPT %d %s -- %d %s  minD %f Natom %d Nbond %d\n",
       mol->filename,Nround,mol->atoms[min_a].num_in_file,mol->atoms[min_a].atomname, mol->atoms[min_b].num_in_file,mol->atoms[min_b].atomname,minD,mol->Natom,mol->Nbond);
*/
    mol->conmap.map[min_a][min_b] = mol->conmap.map[min_b][min_a] = '1';
    mol->atoms[min_a].Nnei_heavy += 1; 
    mol->atoms[min_b].Nnei_heavy += 1; 
    mol->atoms[min_a].Nneighbor += 1; 
    mol->atoms[min_b].Nneighbor += 1; 
    mol->Nbond += 1;
  }
 } while (hit==1);

 /*
 printf("#mol->Nbond %d\n",mol->Nbond);
  */

 /** [3] Assign bond for the atom pair with the minimum distance for Hydrogen ( with distance range constraint )**/ 
 do{
   hit = 0;
   minD = -1.0;
   for (a=0;a<mol->Natom;++a){
     ele_a = mol->atoms[a].one_char_ele;
     if (ele_a == 'H'){
       for (b=0;b<mol->Natom;++b){
         ele_b = mol->atoms[b].one_char_ele;
         if ((a!=b) && (ele_b != 'H')){
           if ((mol->conmap.map[a][b]=='0')&&
               (mol->atoms[a].Nneighbor < Nbond_max[(int)ele_a]) &&
               (mol->atoms[b].Nneighbor < Nbond_max[(int)ele_b])  ){
              Dvdw = mol->dismap.map[a][b];  
/*
        printf("hit %d a %s %d min_b %s %d  Dvdw %f minD %f\n",hit,
          mol->atoms[a].element, mol->atoms[a].num_in_file,
          mol->atoms[b].element, mol->atoms[b].num_in_file,Dvdw,minD); 
 */
             if ((Dvdw>0.80) && (Dvdw<1.2) && ((hit==0) || (Dvdw<minD))) {
                minD = mol->dismap.map[a][b]; min_a = a; min_b = b; hit = 1; 
             }
          } 
        }
      } /* b */ 
    } /* 'H' */
   } /* a */


   if (hit==1){
    /*
     printf(">MAKE_BOND hit %d min_a %s %d min_b %s %d  minD %f\n",hit,
      mol->atoms[min_a].element, mol->atoms[min_a].num_in_file,
      mol->atoms[min_b].element, mol->atoms[min_b].num_in_file,minD); 
     */

      mol->conmap.map[min_a][min_b] = mol->conmap.map[min_b][min_a] = '1';
      mol->Nbond += 1;
      mol->atoms[min_a].Nneighbor += 1; 
      mol->atoms[min_b].Nneighbor += 1; 
    }

 } while (hit==1);

 /*
 printf("#mol->Nbond(with H) %d\n",mol->Nbond);
  */

 /** [4] Assign bond for the atom pair with the minimum distance for hydrogen (without distance range constraint) **/ 
 do{
   hit = 0;
   minD = -1.0;
   for (a=0;a<mol->Natom;++a){
     ele_a = mol->atoms[a].one_char_ele;
     if (ele_a == 'H'){
       for (b=0;b<mol->Natom;++b){
         ele_b = mol->atoms[b].one_char_ele;
         if ((a!=b) && (ele_b != 'H')){
           if ((mol->conmap.map[a][b]=='0')&&
               (mol->atoms[a].Nneighbor < Nbond_max[(int)ele_a]) &&
               (mol->atoms[b].Nneighbor < Nbond_max[(int)ele_b])  ){
              Dvdw = mol->dismap.map[a][b];  
             if ((hit==0) || (Dvdw<minD)) {
                minD = mol->dismap.map[a][b]; min_a = a; min_b = b; hit = 1; 
             }
          } 
        }
      } /* b */ 
    } /* 'H' */
   } /* a */


   if (hit==1){
     /*
      printf(">MAKE_BOND_FINAL hit %d min_a %s %d min_b %s %d  minD %f\n",hit,
        mol->atoms[min_a].element, mol->atoms[min_a].num_in_file,
        mol->atoms[min_b].element, mol->atoms[min_b].num_in_file,minD); 
     */
      mol->conmap.map[min_a][min_b] = mol->conmap.map[min_b][min_a] = '1';
      mol->Nbond += 1;
      mol->atoms[min_a].Nneighbor += 1; 
      mol->atoms[min_b].Nneighbor += 1; 
    }

 } while (hit==1);

 printf("#mol->Nbond(with H) %d\n",mol->Nbond);

 

 /** [5] Malloc mol->bonds (array of struct BOND)  **/ 
 /* printf("#Nbond %d\n",mol->Nbond); */
 mol->bonds = (struct BOND*)malloc(sizeof(struct BOND)*mol->Nbond);
 n = 0;
 for (a=0;a<mol->Natom;++a){
   for (b=a+1;b<mol->Natom;++b){
     if (mol->conmap.map[a][b] != '0'){
       mol->bonds[n].num   = n; 
       mol->bonds[n].anum1 = a; 
       mol->bonds[n].anum2 = b;
       mol->bonds[n].bondtype = mol->conmap.map[a][b];
       mol->bonds[n].bondstereo = '0';
       ++n;
     }
   }
 }

} /* end of Guess_Bonds_from_Atom_XYZ() */



void Guess_Orbital_from_Atom_XYZ(mol)
 struct MOLECULE *mol;
{
 int a,b,i,nei[5],Nnei;
 struct RING *rn;
 float OA[3],OB[3],OC[3],Nvec[3],angle,angle_tole;

 /*** [1] By Bond Planarity ***/
 angle_tole = 10.0;

 for (a=0;a<mol->Natom;++a){
   mol->atoms[a].orbital = ' '; 
   if (mol->atoms[a].one_char_ele != 'H'){
     mol->atoms[a].orbital = '3'; 
     if (mol->atoms[a].Nnei_heavy==3){
       Nnei = 0; 
       for (i=0;i<mol->atoms[a].Nneighbor;++i){
         b = mol->atoms[a].neighbors[i];
         if (mol->atoms[b].one_char_ele != 'H'){
           nei[Nnei] = b;
           Nnei += 1;
          }
        }
        if (Nnei==3){
          sub_vec3(OA,mol->atoms[nei[0]].Pos,mol->atoms[a].Pos);
          sub_vec3(OB,mol->atoms[nei[1]].Pos,mol->atoms[a].Pos);
          sub_vec3(OC,mol->atoms[nei[2]].Pos,mol->atoms[a].Pos);
          cross_vec3(Nvec,OA,OB);
          angle = Angle_bwn_Vec(Nvec,OC);
          /* printf("Nnei %d angle %f\n",Nnei,angle); */
          if (fabs(angle-90.0) < angle_tole) mol->atoms[a].orbital = '2';
        } 
     }
   }
 }

 /*** [2] By Plane Ring Structure ***/
 rn = &(mol->HeadRing);
 while (rn->next != NULL){
   rn = rn->next;
   if (rn->planarity=='p'){
     for (i=0;i<rn->Natom;++i){
       a = rn->num_atoms[i];
       mol->atoms[a].orbital = '2';
     }
   }
 }

} /*  end of Guess_Orbital_from_Atom_XYZ() */



void Set_Aromatic_Ring_by_3D_Planarity(mol)
  struct MOLECULE *mol;
{
 struct RING *rn;
 int a,b,c,i,k;
 float OA0[3],OA1[3],NA[3],OB0[3],OB1[3],NB[3],angle,angle_tole,d;

 /*
    Set_Aromatic_Ring_by_3D_Planarity(mol)
 */

 angle_tole = 20.0;  /** degree **/


 rn = &(mol->HeadRing);
 while (rn->next != NULL){
   rn = rn->next;

   /** (1) Calculate center position (cpos) ***/
   for (i=0;i<rn->Natom;++i){
    a = rn->num_atoms[i];
  }  
  for (k=0;k<3;++k) rn->cpos[k] = rn->nvec[k] = 0.0;
   for (i=0;i<rn->Natom;++i){
     for (k=0;k<3;++k) rn->cpos[k] += mol->atoms[rn->num_atoms[i]].Pos[k];
   }
   for (k=0;k<3;++k) rn->cpos[k] /= rn->Natom;

  rn->rg = 0.0;

  for (i=0;i<rn->Natom;++i){
    for (k=0;k<3;++k){
      d = mol->atoms[rn->num_atoms[i]].Pos[k] - rn->cpos[k];
      rn->rg += d*d;
    }
  }

  rn->rg /= rn->Natom;
  if (rn->rg > 0.0) rn->rg = sqrt(rn->rg);


  /** (2) Check Planarity ***/
        if (rn->Natom <5||(rn->Natom>6))    { rn->planarity = 'N'; rn->aromatic = '-';}
   else {
     rn->planarity = 'p';
     rn->aromatic  = 'A';

/*
     printf(">ring[%d] (",rn->num);
     for (a=0;a<rn->Natom;++a){
       printf(" %d",mol->atoms[rn->num_atoms[a]].num_in_file);
     }
     printf(")\n");
*/

     for (a=0;a<rn->Natom;++a){
       sub_vec3(OA0,mol->atoms[rn->num_atoms[a]].Pos,rn->cpos);
       sub_vec3(OA1,mol->atoms[rn->num_atoms[(a+1)%rn->Natom]].Pos,rn->cpos);
       cross_vec3(NA,OA0,OA1);
       normalize_vec3(NA); 
       for (k=0;k<3;++k) rn->nvec[k] += NA[k];
       for (b=a+1;b<rn->Natom;++b){
         sub_vec3(OB0,mol->atoms[rn->num_atoms[b]].Pos,rn->cpos);
         sub_vec3(OB1,mol->atoms[rn->num_atoms[(b+1)%rn->Natom]].Pos,rn->cpos);
         cross_vec3(NB,OB0,OB1);
         normalize_vec3(NB); 
         angle =  Angle_bwn_Vec(NA,NB);
/*
         printf("#rn->num %d atom_num a %d b %d angle %f angle_tole %f\n",
          rn->num,  mol->atoms[rn->num_atoms[a]].num_in_file, mol->atoms[rn->num_atoms[b]].num_in_file,angle,angle_tole);
*/
         if (angle > angle_tole){
            rn->planarity = 'N';
            rn->aromatic  = '-';
         }

       }
     }


   /** (3) Set normal vector(nvec) for "plane" ring  ***/
     if (rn->planarity=='p'){
       for (i=0;i<rn->Natom;++i){
         c = rn->num_atoms[i];
         mol->atoms[c].ring = 'p';
       }
     normalize_vec3(rn->nvec);
     }

   }

 }

} /* end of Set_Aromatic_Ring_by_3D_Planarity() */








void Set_DAMRL_from_3D_structure(mol)
 struct MOLECULE *mol;
{
 /*
   >> CAUTION << 
     The functions:
        Set_Nneighbor_CHNOSP() 
        Guess_Orbital_from_Atom_XYZ() 
 
     should performed before executing this function.

 */
 int i,a,n;
 /* printf("#Set_DAMRL_from_3D_structure(mol)\n");  */
 /** [1] Atom-based rurle **/
 for (a=0;a<mol->Natom;++a){
   /** ['C'] **/
   if (mol->atoms[a].one_char_ele == 'C'){
          if (mol->atoms[a].aromatic=='A') mol->atoms[a].DAMRL = 'R';
     else                                  mol->atoms[a].DAMRL = 'L';
   }

   /** ['O'] **/
   else if (mol->atoms[a].one_char_ele == 'O'){
    if (mol->atoms[a].Nnei_heavy ==1){
         n = 0;
         for (i=0;i<mol->atoms[a].Nneighbor;++i){
            if (mol->atoms[mol->atoms[a].neighbors[i]].one_char_ele != 'H') n = mol->atoms[a].neighbors[i];
         }
     
        
         if ((mol->atoms[n].one_char_ele=='P')||(mol->atoms[n].one_char_ele=='S')) mol->atoms[a].DAMRL = 'A';

         else if (mol->atoms[n].orbital =='2') {
           if (mol->atoms[n].aromatic =='A') mol->atoms[a].DAMRL = 'M';
             else                            mol->atoms[a].DAMRL = 'A';
         } 
         else if (mol->atoms[n].orbital =='3') mol->atoms[a].DAMRL = 'M';
     }
     else if (mol->atoms[a].Nnei_heavy ==2) mol->atoms[a].DAMRL = 'A';
/*
      printf("#n %d orbital %c a %d O DAMRL %c\n",mol->atoms[n].num_in_file,mol->atoms[n].orbital,mol->atoms[a].num_in_file,mol->atoms[a].DAMRL); 
 */ 
   }

   /** ['N'] **/
   else if (mol->atoms[a].one_char_ele == 'N'){
          if (mol->atoms[a].Nnei_heavy==1) { 
        if (distance_vec3(mol->atoms[a].Pos,mol->atoms[mol->atoms[a].neighbors[0]].Pos)<1.25) 
               mol->atoms[a].DAMRL = 'L'; /* C-[triple-bond]-N */  
        else   mol->atoms[a].DAMRL = 'D'; /* -NH2 */
     }
     else if (mol->atoms[a].Nnei_heavy==2){ 
            if (mol->atoms[a].aromatic =='A') mol->atoms[a].DAMRL = 'A';
       else if (mol->atoms[a].NneiN >0 )      mol->atoms[a].DAMRL = 'A';
       else                                   mol->atoms[a].DAMRL = 'D';
     }
     else if (mol->atoms[a].Nnei_heavy==3){  
       if (mol->atoms[a].aromatic =='A') mol->atoms[a].DAMRL = 'R';
                                   else  mol->atoms[a].DAMRL = 'L';
     }
     else mol->atoms[a].DAMRL = 'L';
   }

    /** ['P','S','F','c'(Cl),'b'(Br),'I']  **/
   else if ((mol->atoms[a].one_char_ele == 'P') || (mol->atoms[a].one_char_ele == 'S')||
            (mol->atoms[a].one_char_ele == 'F') || (mol->atoms[a].one_char_ele == 'c') ||
            (mol->atoms[a].one_char_ele == 'b') || (mol->atoms[a].one_char_ele == 'I') )
      mol->atoms[a].DAMRL = 'L';

   /** ['H']  **/
   else if (mol->atoms[a].one_char_ele == 'H') mol->atoms[a].DAMRL = 'H';

   /** [others]  **/
   else mol->atoms[a].DAMRL = 'X';


 }

} /* end of Set_DAMRL_from_3D_structure() */





void Set_DAMRL_from_3D_RING(mol)
 struct MOLECULE *mol;
{
 /*
   >> CAUTION << 
     The functions:
        Set_Nneighbor_CHNOSP() 
        Guess_Orbital_from_Atom_XYZ() 
        Set_DAMRL_from_3D_structure() 
 
     should performed before executing this function.

 */
 int i,j,a,b;
 int n_N,n_satu,n_unsatuN,n_bondO; 
 int memb_unsatuN[5],memb_bondO[5];
 struct RING *rn;

 /* printf("#Set_DAMRL_from_3D_RING(mol)\n"); */
 rn = &(mol->HeadRing);
 while (rn->next != NULL){
   rn = rn->next;

 /** 
  (1) Count several numbers (n_N, n_satu, n_unsatuN, n_bondO) 
   
  * "saturated polar atom": N with Nnei_heavy=3, O with Nnei_heavy=2, S with Nnei_heavy=2.
  * n_N       : Number of nitrogen
  * n_satu    : Number of saturated polar atoms 
  * n_unsatuN : Number of unsaturated nitrogen
  * n_bondO   : Number of ring-bonded O
 
 **/

   if (((rn->Natom==5) || (rn->Natom==6))&& (rn->planarity=='p')){

     n_N = n_satu = n_unsatuN = n_bondO = 0; 

     for (i=0;i<rn->Natom;++i){
       a = rn->num_atoms[i];
       mol->atoms[a].mark = 0;
       if (mol->atoms[a].one_char_ele=='N'){ 
           n_N += 1;
           if (mol->atoms[a].Nnei_heavy==3) n_satu += 1; 
           else{
             memb_unsatuN[n_unsatuN] = a; 
             n_unsatuN += 1;
           }
        }
       if ((mol->atoms[a].one_char_ele=='O')&&(mol->atoms[a].Nnei_heavy==2))  n_satu += 1; 
       if ((mol->atoms[a].one_char_ele=='S')&&(mol->atoms[a].Nnei_heavy==2))  n_satu += 1; 

       if ((mol->atoms[a].Nneighbor<4)&&(mol->atoms[a].NneiO>0)){
         for (j=0;j<mol->atoms[a].Nneighbor;++j){
           b = mol->atoms[a].neighbors[j];
           if ((mol->atoms[b].one_char_ele=='O') && (mol->atoms[b].Nnei_heavy==1) && (mol->atoms[b].ring!='p')){
              memb_bondO[n_bondO] = b;
              mol->atoms[a].mark = 1;  /* Ring-carbon bonded to O, has mark = 1 */
              n_bondO += 1;
           }
         }  
       }
     }

     /**
      (2) [Nring5]: Nitrogen-containing 5-atom ring
       If the ring  contains no saturaged polar atom (n_satu==0),
         If Number of nitrogen==1, the DAMRL  for the N  is  'D',
                      otherwise, the DAMRLs for the Ns are 'M'.

      If the ring contains one saturated polar atom (n_satu==1),
        For the nitrogen with Nnei_heavy==3, its DAMRL is  'L',
        For other nitrogens, their DAMRL is  'A'.

     **/

     if ((rn->Natom==5) && (n_N>0)){
       /*printf("#ring %d n_N %d n_satu %d n_unsatuN %d\n",rn->num,n_N,n_satu,n_unsatuN);*/    
       if (n_satu==0){
              if (n_unsatuN==1) {mol->atoms[memb_unsatuN[0]].DAMRL = 'D';}
         else { 
           for (i=0;i<n_unsatuN;++i){
              mol->atoms[memb_unsatuN[i]].DAMRL = 'M';  
              /* printf("#set %d to 'M'\n",mol->atoms[memb_unsatuN[i]].num_in_file); */
           } 
         }
       }

        if (n_satu>=1){ for (i=0;i<n_unsatuN;++i){ mol->atoms[memb_unsatuN[i]].DAMRL = 'A';} }
     }

    /**
      (3) [Nring56=O]: Nitrogen-containing 5,6-atom ring, having bonded O atoms with Nnei_heavy=2
       
       If (NbondedO == Nsaturated) 
        For the nitrogen with Nnei_heavy==3, its DAMRL is  'L',
        For other nitrogens, their DAMRL is  'A'.
       If the ring  contains no saturaged polar atom,
         If Number of nitrogen==1, the DAMRL  for the N  is  'D',
                      otherwise, the DAMRLs for the Ns are 'M'.

      If the ring contains one saturated polar atom,

     **/
     if (((rn->Natom==5)||(rn->Natom==6)) && (n_N>0) && (n_bondO >0)){    
       /* printf("#ring %d Natom %d n_N %d n_bondO %d\n",rn->num,rn->Natom,n_N,n_bondO); */    
       for (i=0;i<n_bondO;++i) mol->atoms[memb_bondO[i]].DAMRL = 'A';

       if (n_bondO == n_satu){
          for (i=0;i<n_unsatuN;++i) mol->atoms[memb_unsatuN[i]].DAMRL = 'A'; 
       }

       if (n_bondO > n_satu){
           if (n_unsatuN==1) {mol->atoms[memb_unsatuN[0]].DAMRL = 'D';}
           else{
             for (i=0;i<n_unsatuN;++i){ 
               b = memb_unsatuN[i];
               mol->atoms[b].DAMRL = 'A';
               for (j=0;j<mol->atoms[b].Nneighbor;++j){
                 if (mol->atoms[mol->atoms[b].neighbors[j]].mark==1) mol->atoms[b].DAMRL = 'D';
               }
             }
           } 
       }

     }


   } /* if */
 
 } /* rn */

} /* end of Set_DAMRL_from_3D_RING() */






int atom_num_FROM_atom_num_in_file(mol,atom_num_in_file)
  struct MOLECULE *mol;
  int atom_num_in_file;
{
 int i;

 for (i=0;i<mol->Natom;++i){
   if (mol->atoms[i].num_in_file == atom_num_in_file){return(i);}
 }
 return(-1);
} /* end of atom_num_FROM_atom_num_in_file() */








float Angle_bwn_Vec(A,B)   
 float A[3],B[3];
{ float dot_prod,normA,normB,cosAB;
  /*
   This function returns from 0 to 90 degrees.
   If vector B is inverse direction of A(B == -A), it returns 0 degree.
  */
  normA    = A[0]*A[0] + A[1]*A[1] + A[2]*A[2];
  normB    = B[0]*B[0] + B[1]*B[1] + B[2]*B[2];
  dot_prod = A[0]*B[0] + A[1]*B[1] + A[2]*B[2];
  cosAB = dot_prod/sqrt(normA)/sqrt(normB);
  if (cosAB < 0.0) cosAB *= -1.0;
  return(acos(cosAB)*180.0/M_PI);
}





void Element_from_PDB_Atomname(element,atomname)
  char *element;
  char *atomname; 
{
/*    
>>> EXAMPLES OF PDB FILES <<<
>>pdb1aa9.ent<<
HETATM 2727 MG    MG A 173     129.369  -1.143  10.024  1.00  3.45          MG
HETATM 2728  PB  GDP A 180     132.580  -0.884  10.946  1.00  1.28           P
HETATM 2729  O1B GDP A 180     131.602  -1.788  11.591  1.00  2.05           O
HETATM 2730  O2B GDP A 180     131.979   0.121  10.041  1.00  1.89           O
HETATM 2734  O1A GDP A 180     132.281  -0.115  13.953  1.00  2.00           O
HETATM 2736  O5' GDP A 180     134.673   0.349  13.942  1.00  1.40           O
HETATM 2757 H5'' GDP A 180     134.197  -0.301  15.838  1.00  1.76           H
HETATM 2758  H4' GDP A 180     134.640   1.663  17.022  1.00  1.33           H
HETATM 2760 HO3' GDP A 180     132.224   1.890  16.425  1.00  1.95           H
HETATM 2761  H2' GDP A 180     134.224   3.920  13.786  1.00  1.22           H
HETATM 2762 HO2' GDP A 180     134.163   5.712  15.429  1.00  1.71           H
HETATM 2763  H1' GDP A 180     135.817   4.485  16.154  1.00  1.00           H
HETATM 2765  HN1 GDP A 180     140.538   7.338  14.020  1.00  1.32           H
HETATM 2766 HN21 GDP A 180     140.460   7.807  16.187  1.00  1.44           H
HETATM 2767 HN22 GDP A 180     139.262   7.113  17.256  1.00  1.31           H
>> pdb4aai.ent <<
ATOM      9  H   MET A   1       9.517  18.716 -26.058  1.00  0.00           H
ATOM     10  HA  MET A   1       9.836  17.425 -24.009  1.00  0.00           H
ATOM     57  HA  SER A   4       1.442  13.939 -19.192  1.00  0.00           H
ATOM     58  HB2 SER A   4       0.861  14.036 -22.152  1.00  0.00           H
ATOM     59  HB3 SER A   4       0.707  15.457 -21.119  1.00  0.00           H
ATOM     60  HG  SER A   4      -0.721  13.020 -20.965  1.00  0.00           H
ATOM   2266  HA  PRO B  60      -6.046  15.537  10.707  1.00  0.00           H
ATOM   2267  HB2 PRO B  60      -6.055  17.031  12.445  1.00  0.00           H
ATOM   2268  HB3 PRO B  60      -4.429  17.409  11.865  1.00  0.00           H
ATOM   2269  HG2 PRO B  60      -4.832  16.612  14.376  1.00  0.00           H
ATOM   2270  HG3 PRO B  60      -3.409  16.072  13.464  1.00  0.00           H
ATOM   2271  HD2 PRO B  60      -4.254  14.006  14.051  1.00  0.00           H
ATOM   2272  HD1 PRO B  60      -5.925  14.594  14.109  1.00  0.00           H
ATOM   2301  CG2 ILE B  62      -5.021  10.552   6.917  1.00  0.00           C
ATOM   2302  CD1 ILE B  62      -2.865  10.208  10.115  1.00  0.00           C
ATOM   2303  HA  ILE B  62      -2.225  11.381   7.606  1.00  0.00           H
ATOM   2304  HB  ILE B  62      -4.964  11.559   8.787  1.00  0.00           H
ATOM   2305 HG12 ILE B  62      -3.147   9.202   8.279  1.00  0.00           H
ATOM   2306 HG13 ILE B  62      -4.567   9.244   9.319  1.00  0.00           H
ATOM   2307 HG21 ILE B  62      -4.334  10.482   6.087  1.00  0.00           H
ATOM   2308 HG22 ILE B  62      -5.803  11.258   6.680  1.00  0.00           H
ATOM   2309 HG23 ILE B  62      -5.458   9.581   7.104  1.00  0.00           H
ATOM   2310 HD11 ILE B  62      -3.462  10.736  10.845  1.00  0.00           H
ATOM   2311 HD12 ILE B  62      -2.064  10.850   9.772  1.00  0.00           H
>> pdb3arc.ent <<
HETATM41688  O1  OEX A 601     -26.510 -36.601 204.050  1.00 22.48           O
HETATM41689 CA1  OEX A 601     -27.969 -36.452 202.243  1.00 24.57          CA
HETATM41690 MN1  OEX A 601     -24.977 -35.548 203.849  1.00 22.62          MN
HETATM41691  O2  OEX A 601     -28.560 -34.524 203.696  1.00 25.22           O
HETATM41692 MN2  OEX A 601     -27.388 -35.240 205.326  1.00 22.88          MN
HETATM41693  O3  OEX A 601     -25.808 -34.096 204.540  1.00 23.27           O
HETATM41694 MN3  OEX A 601     -27.257 -33.264 203.226  1.00 23.49          MN
HETATM41695  O4  OEX A 601     -28.740 -32.584 201.922  1.00 26.62           O
HETATM41696 MN4  OEX A 601     -27.599 -33.237 200.276  1.00 26.26          MN
>> pdb1aa5.ent <<
HETATM  133  HN1 3FG A   7       1.904   2.986   5.854  1.00  5.72           H
HETATM  134  HA  3FG A   7       0.691   0.779   4.801  1.00  6.88           H
HETATM  135  HD1 3FG A   7       4.075   1.650   1.428  1.00  5.99           H
HETATM  136  HZ  3FG A   7       6.148   0.117   3.505  1.00  5.61           H
HETATM  137  HD2 3FG A   7       6.605  -0.752   5.609  1.00  7.09           H
HETATM  138  HG2 3FG A   7       3.497  -0.129   6.511  1.00  6.76           H
HETATM  139  HOT 3FG A   7       1.007   0.445   8.470  1.00  9.61           H
>> pdb3a0w.ent <<
HETATM 2502 HG  AEMC A 801      49.554  58.731  15.205  0.30 29.81          HG
HETATM 2503 HG  BEMC A 801      49.086  63.531  15.237  0.30 44.78          HG
HETATM 2504  C1 AEMC A 801      48.824  56.764  16.257  0.30 27.68           C
HETATM 2505  C1 BEMC A 801      49.487  64.170  17.491  0.30 43.48           C
HETATM 2506  C2 AEMC A 801      49.010  56.925  17.750  0.30 28.92           C
HETATM 2507  C2 BEMC A 801      51.053  63.827  17.815  0.30 43.57           C
HETATM 2508 HG   EMC A 802      50.971  48.709  -4.694  0.80 25.19          HG
>> pdb1cc8.ent <<
HETATM  569 HG    HG A  74       5.897   0.005   3.783  1.00 10.60          HG
HETATM  570  C1  BEN A 186       6.778  10.510  20.665  1.00  4.96           C
HETATM  571  C2  BEN A 186       5.994   9.710  19.842  1.00  5.48           C
>> pdb1o7t.ent <<
HETATM21403  OBD HF5 A1310      12.209  52.345 -17.389  1.00 55.42           O
HETATM21404 HFA  HF5 A1310      10.810  51.834 -13.339  1.00 33.27          HF
HETATM21405  O00 HF5 A1310      12.522  51.019 -14.388  1.00 66.11           O
HETATM21406  OAB HF5 A1310      10.204  50.460 -15.311  1.00 42.43           O
HETATM21407  OAC HF5 A1310      12.821  52.802 -12.248  1.00 34.32           O
HETATM21408  OAD HF5 A1310      10.622  53.390 -14.955  1.00 86.30           O
HETATM21409  OAE HF5 A1310      10.540  53.809 -11.877  1.00 56.64           O
HETATM21410  OA1 HF5 A1310       8.751  50.422 -13.681  1.00 37.07           O
HETATM21411 HFB  HF5 A1310      12.391  50.336 -16.504  1.00 43.82          HF
HETATM21412  OBC HF5 A1310      14.747  50.922 -16.256  1.00 64.16           O
HETATM21413  OB1 HF5 A1310      12.516  47.750 -16.386  1.00 39.29           O
HETATM21414  OB2 HF5 A1310       9.974  50.462 -17.864  1.00 25.83           O
HETATM21415  OB3 HF5 A1310      14.284  50.097 -18.387  1.00 46.74           O
HETATM21416 HFC  HF5 A1310      14.480  51.988 -14.021  1.00 44.44          HF
HETATM21417  OCD HF5 A1310      14.371  54.160 -14.611  1.00 53.36           O
HETATM21418  OC1 HF5 A1310      16.837  52.625 -14.715  1.00 63.62           O
HETATM21419  OC2 HF5 A1310      15.120  54.166 -11.785  1.00 40.71           O
HETATM21420 HFD  HF5 A1310      12.141  54.214 -15.784  1.00 65.07          HF
HETATM21421  ODE HF5 A1310      11.786  56.117 -14.349  1.00 99.50           O
HETATM21422  OD1 HF5 A1310      13.605  55.217 -17.842  1.00 89.38           O
HETATM21423  OD2 HF5 A1310      11.175  56.187 -17.319  1.00 68.46           O
HETATM21424 HFE  HF5 A1310      10.581  56.275 -12.625  1.00 99.50          HF
HETATM21425  OE1 HF5 A1310      12.578  56.675 -11.378  1.00 85.88           O
HETATM21426  OE2 HF5 A1310       8.798  55.140 -13.958  1.00 99.50           O
HETATM21427  OE3 HF5 A1310       9.748  58.496 -13.264  1.00 84.21           O
>>pdb1tmn.ent<<
HETATM 2454  N1  0ZN E 317      52.952  15.765  -3.983  1.00 18.44           N
HETATM 2455  CA2 0ZN E 317      53.530  14.448  -4.298  1.00 23.01           C
HETATM 2456  C1  0ZN E 317      52.643  13.531  -5.133  1.00 26.89           C
HETATM 2457  O1  0ZN E 317      51.572  14.027  -5.605  1.00 22.68           O
HETATM 2458  CB3 0ZN E 317      54.101  13.735  -3.037  1.00 23.46           C
HETATM 2459  CG2 0ZN E 317      52.943  13.258  -2.164  1.00 19.83           C
HETATM 2460 CD11 0ZN E 317      51.832  13.908  -1.823  1.00 24.81           C
HETATM 2461 CD21 0ZN E 317      52.798  11.977  -1.642  1.00 24.95           C
HETATM 2462  NE1 0ZN E 317      50.892  12.989  -1.314  1.00 25.46           N
HETATM 2463 CE21 0ZN E 317      51.442  11.840  -1.286  1.00 25.54           C
HETATM 2464  CE3 0ZN E 317      53.723  10.946  -1.480  1.00 30.14           C
HETATM 2465 CZ21 0ZN E 317      50.904  10.638  -0.855  1.00 28.63           C
HETATM 2466  CZ3 0ZN E 317      53.213   9.741  -0.964  1.00 30.85           C
HETATM 2467  CH2 0ZN E 317      51.831   9.584  -0.690  1.00 30.40           C
HETATM 2468  OXT 0ZN E 317      53.142  12.469  -5.652  1.00 24.16           O
HETATM 2469 CA    CA E 318      61.303  22.116   4.786  1.00 13.41          CA
HETATM 2470 CA    CA E 319      61.569  23.253   8.472  1.00 14.54          CA
HETATM 2471 CA    CA E 320      35.745  32.533  15.823  1.00 12.78          CA
HETATM 2472 CA    CA E 321      57.297  12.904  10.398  1.00 16.76          CA
HETATM 2473 ZN    ZN E 322      54.519  20.316  -7.288  1.00 14.25          ZN
HETATM 2474  O   HOH E 331      68.539  16.913 -21.003  1.00 18.54           O
>>pdb1cll.ent<<
HETATM 1135 CA    CA A 149       1.708  47.776  24.197  1.00 12.07          CA
HETATM 1136 CA    CA A 150      -2.112  44.438  13.360  1.00 13.42          CA
HETATM 1137 CA    CA A 151      30.463  11.962  10.473  1.00 25.88          CA
HETATM 1138 CA    CA A 152      29.181  17.963   0.804  1.00 29.77          CA
HETATM 1139  C1  EOH A 153       7.868  37.805  18.104  1.00 63.73           C
HETATM 1140  C2  EOH A 153       6.465  38.277  17.751  1.00 64.50           C
HETATM 1141  H21 EOH A 153       6.499  39.538  17.106  1.00 64.47           H
>>pdb4fik.ent<<
ATOM   1677  CB  CYS A 206      -4.229   8.811  22.820  1.00  7.14           C
ATOM   1678  SG  CYS A 206      -4.184   7.846  21.278  1.00  7.76           S
HETATM 2175  S1 AD2S A 304      -8.717   9.120   6.669  0.71 13.76           S
HETATM 2176  C2 AD2S A 304     -10.591  10.818   7.506  0.71 12.18           C
HETATM 2177  S2 AD2S A 304      -9.076   7.758   8.098  0.71 14.67           S
HETATM 2178  C3 AD2S A 304      -9.260  10.594   7.339  0.71 13.01           C
HETATM 2179  O3 AD2S A 304     -10.490  14.182   8.981  0.71 15.27           O

>> pdb4e7r.ent <<
HETATM 4678 CL2  0NW H 302      23.679   6.056  26.437  1.00 29.41          CL
HETATM 4679  C36 0NW H 302      23.660   3.431  25.705  1.00 30.99           C
HETATM 4680 CL1  0NW H 302      23.546   0.734  25.512  1.00 48.22          CL

>> pdb1pxi.ent <<
HETATM 2367 CL7AACK1 A 500      14.171  44.275  29.729  0.73 13.63          CL
HETATM 2370  S2AACK1 A 500      14.041  42.285  27.535  0.73 22.98           S
HETATM 2372 CL6AACK1 A 500      13.557  41.890  24.844  0.73 13.46          CL
HETATM 2373  C5AACK1 A 500      13.388  44.250  25.907  0.73 16.88           C

>> pdb2gde.ent <<
HETATM 2360  C30 SN3 H 401      18.158 -16.049  26.995  1.00 44.63           C
HETATM 2361 CL31 SN3 H 401      19.334 -14.269  24.819  1.00 47.30          CL
HETATM 2362  N32 SN3 H 401      16.043 -15.948  23.241  1.00 50.01           N

>> pdb4ht0.ent <<
HETATM 2155  F13 V50 A 304      -2.858   1.546  16.530  1.00 33.38           F
HETATM 2163  F11 V50 A 304      -6.992   3.162  15.322  1.00 35.74           F
HETATM 2164  C1  V50 A 304      -5.067   4.374  14.600  1.00 31.51           C

>> pdb3rz7.ent <<
HETATM 2098 F2'1 RZ7 A 262      20.534   7.261  14.299  1.00 25.62           F
HETATM 2099 F3'1 RZ7 A 262      18.846   9.517  12.136  1.00 27.91           F
HETATM 2100 F4'1 RZ7 A 262      20.745   9.802  15.258  1.00 29.96           F
HETATM 2101 F5'1 RZ7 A 262      21.189  11.328  12.368  1.00 32.43           F
HETATM 2102 F6'1 RZ7 A 262      22.957  11.252  15.526  1.00 43.46           F
HETATM 2103 F2'2 RZ7 A 262      18.702   8.275  14.563  1.00 21.80           F

>> pdb1mbd.ent <<
HETATM 1237 FE   HEM A 155      15.271  27.962   0.622  1.00  7.86          FE
HETATM 1238  CHA HEM A 155      16.869  31.030   0.421  1.00  4.49           C
HETATM 1242  NA  HEM A 155      16.206  29.133   1.939  1.00  7.65           N


*/

/*
>>> SUMMARY <<<
ATOM      9  H   MET A   1      -> 'H'
ATOM     10  HA  MET A   1      -> 'H'
HETATM 2678  HN5 X37 A1480      -> 'H'
HETATM  139  HOT 3FG A   7      -> 'H'
HETATM 2679 HN5A X37 A1480      -> 'H'
ATOM   2305 HG12 ILE B  62      -> 'H'
ATOM     60  HG  SER A   4      -> 'H'
HETATM 2766 HN21 GDP A 180      -> 'H'
HETATM 2767 HN22 GDP A 180      -> 'H'
HETATM 2373 HG    HG A 601      -> 'HG'
HETATM21404 HFA  HF5 A1310      -> 'HF'
HETATM21424 HFE  HF5 A1310      -> 'HF'
HETATM 2374  C1  BNZ A 602      -> 'C'
HETATM 2375  C2  BNZ A 602      -> 'C'
HETATM 5274  C4  GCP A1749      -> 'C'
HETATM 5280  C3B GCP D1749      -> 'C'
HETATM 2460 CD11 0ZN E 317      -> 'C'
HETATM 2463 CE21 0ZN E 317      -> 'C'
HETATM 2465 CZ21 0ZN E 317      -> 'C'
HETATM 4680 CL1  0NW H 302      -> 'CL'
HETATM 3647 CL    CL A 800      -> 'CL'
HETATM 2372 CL6AACK1 A 500      -> 'CL'
HETATM 2367 CL7AACK1 A 500      -> 'CL'
HETATM 2361 CL31 SN3 H 401      -> 'CL'
HETATM 2228  N1  HMD A 400      -> 'N'
HETATM 2677  N5  X37 A1480      -> 'N'
HETATM 2226  O1  HMD A 400      -> 'O'
HETATM 3646  O5  PG4 A 500      -> 'O'
HETATM 5277  O1G GCP D1749      -> 'O'
HETATM 3648  O   HOH A 501      -> 'O'
HETATM    1  BR  MOL A   1      -> 'BR'
HETATM 2225 BR1  HMD A 400      -> 'BR'
HETATM 5275 MG    MG A1750      -> 'MG'
HETATM 5276  PG  GCP D1749      -> 'P'
HETATM 5281  PB  GCP D1749      -> 'P'
HETATM 7746  K     K A1525      -> 'K'
HETATM 7747  P   JLN A1526      -> 'P'
HETATM41689 CA1  OEX A 601      -> 'CA'
HETATM 1135 CA    CA A 149      -> 'CA'
HETATM41690 MN1  OEX A 601      -> 'MN'
ATOM   1678  SG  CYS A 206      -> 'S'
HETATM 2175  S1 AD2S A 304      -> 'S'
HETATM 2177  S2 AD2S A 304      -> 'S'
HETATM 2155  F13 V50 A 304      -> 'F'
HETATM 2098 F2'1 RZ7 A 262      -> 'F'
HETATM 1237 FE   HEM A 155      -> 'FE'



>> Rule to distinguish hydrogens(H) or carbons(C) and others (HG and HF, CA and CL) << .
 (1) If the first symbol is 'space' and the second is 'H' or 'C' (' H  ', ' HA  ',  ' HN5', ' C  ',' CA ') 
      -> element := 'H' or 'C' 
 (2) If the first symbol is 'H' or 'C'

    (2a) if it starts with 'CL', ('CL  ', 'CL7A','CL7A') 
         element := 'CL'
    (2b) else if the length of atomname == 4 ('HN5A', 'HG12','CD11','CZ21') 
      -> element := 'H' or 'C'
    (3c) else if the length of atomname < 4  ('HG  ', 'HFA ',  'HFE ', 'CL  ' 'CA  ','CA1 ') 
      -> element := the first and second symobol. (such as 'HG', 'HF')
*/
  int i,len;

  len = 0;
  for (i=0;i<strlen(atomname);++i){
    if ((atomname[i]!=' ')&&(atomname[i] != '\0')){ len += 1;}
  }

  if (atomname[0]!=' '){
    if ((atomname[0]=='H')||(atomname[0]=='C')){
      if ((atomname[0]=='C')||(atomname[0]=='L')){
        element[0] = 'C'; element[1] = 'L'; element[2] = '\0';
      }
      else if (len==4){
       /* (2) the first symbol is 'H' or 'C' and the length of atomname == 4 ('HN5A', 'HG12','CD11','CE12')  */
        element[0] = atomname[0];
        element[1] = '\0';
      }
      else if (len<4){
       /* (3) the first symbol is 'H' or 'C' and the length of atomname < 4  ('HG  ', 'HFA ',  'HFE ', 'CA  ','CA1 ')  */
        element[0] = atomname[0]; 
        element[1] = atomname[1];
        element[2] = '\0';
      }
    }
    else{
      if (isalpha(atomname[1])){
        /* 'MN1 ','BR1 ' */
        element[0] = atomname[0];
        element[1] = atomname[1];
        element[2] = '\0';
      }
      else{
        /* 'F2'1' */
        element[0] = atomname[0];
        element[1] = '\0';
      }
    }
  }
  else if (atomname[0]==' '){  
        if ((atomname[1]=='B') && (atomname[2]=='R'))  sprintf(element,"BR"); /* ' BR ' */
   else if ((atomname[1]=='C') && (atomname[2]=='L'))  sprintf(element,"CL"); /* ' CL ' */
   else{ /* ' H  ', ' HA  ', ' C1 ', ' O  ', ' O1G ', ' PG ', ' PB ' */
     element[0] = atomname[1];
     element[1] = '\0';
   }
 }

 /* printf("#atomname '%s' --> element '%s'\n",atomname,element); */

} /* end of Element_from_PDB_Atomname() */



void Set_Resi_Chain_Rnum_to_Molecule(mol,new_resi,new_chain,new_rnum)
  struct MOLECULE *mol;
  char new_resi[4];
  char new_chain;
  char new_rnum[6];
{
  int a,i;
/*
  char  resi[4];       : residue name  
  char  rnum[6];       : residue number 
 
  NOTE: rnum[] needs a space at the head and the tail.
  For example, if new_rnum[] = '999', mol->atoms[a].rnum[] = ' 999 '.

*/


 /*
  printf("#void Set_Resi_Chain_Rnum_to_Molecule(mol,new_resi '%s',new_chain '%c', new_rnum '%s')\n",new_resi,new_chain,new_rnum);
  */
  for (a=0;a<mol->Natom;++a){
    /* printf("#a %d '%s' '%c' '%s'",a,mol->atoms[a].resi,mol->atoms[a].chain,mol->atoms[a].rnum); */
    for (i=0;i<4;++i){mol->atoms[a].resi[i] = new_resi[i];}
    mol->atoms[a].resi[3] = '\0';
    mol->atoms[a].chain = new_chain;
    mol->atoms[a].rnum[0] = ' ';
    for (i=1;i<6;++i){ mol->atoms[a].rnum[i] = new_rnum[i-1];}
    mol->atoms[a].rnum[4] = ' ';
    mol->atoms[a].rnum[5] = '\0';
    /* printf(" --> a %d '%s' '%c' '%s'\n",a,mol->atoms[a].resi,mol->atoms[a].chain,mol->atoms[a].rnum); */
  }
} /* end of Set_Resi_Chain_Rnum_to_Molecule() */



void Set_Unique_atomname_to_Molecule(mol)
  struct MOLECULE *mol;
{
 int a,e,i,len;
 int None_char_ele[256];
/*
  Make unique atomname using [one_char_ele] and [None_char_ele],
  such as ' O1 ', ' C1 ', ' C2 ', ....
>> Example <<
HETATM    1  O1  MOL A   1     -34.154  11.282   6.661  0.00  1.00           O  O1
HETATM    2  C1  MOL A   1     -32.902  10.456   6.677  0.00  2.00           C   C
HETATM    3  C2  MOL A   1     -32.992   8.960   6.733  0.00  3.00           C   C
HETATM    4  N1  MOL A   1     -33.972   8.301   7.657  0.00  4.00           N   N
HETATM    5  C3  MOL A   1     -33.662   6.957   8.246  0.00  5.00           C   C
HETATM    6  C4  MOL A   1     -33.382   5.790   7.346  0.00  6.00           C   C
HETATM    7  C5  MOL A   1     -33.631   6.780   9.735  0.00  7.00           C   C
HETATM    8  C6  MOL A   1     -31.561  11.126   6.639  0.00  8.00           C   C
HETATM    9  O2  MOL A   1     -30.310  10.299   6.601  0.00  9.00           O   O
 */


 /* printf("#Set_Unique_atomname_to_Molecule(mol)\n"); */
 for (e=0;e<256;++e){None_char_ele[e] = 0;}
 
 for (a=0;a<mol->Natom;++a){
   e = (int)mol->atoms[a].one_char_ele;
   None_char_ele[e] += 1; 
   if (strlen(mol->atoms[a].element)==1){ 
     sprintf(mol->atoms[a].atomname," %s%d",mol->atoms[a].element,None_char_ele[e]);
   }
   else{
     sprintf(mol->atoms[a].atomname,"%s%d",mol->atoms[a].element,None_char_ele[e]);
   }
   len = (int)strlen(mol->atoms[a].atomname);
   for (i=len;i<4;++i) {mol->atoms[a].atomname[i] = ' '; }
   mol->atoms[a].atomname[4] = '\0';
   /*
   printf("#%s %c e %d Ne %d --> '%s' len %d\n",mol->atoms[a].element,mol->atoms[a].one_char_ele,e,None_char_ele[e],mol->atoms[a].atomname,len);
   */
 }

} /* end of Set_Unique_atomname_to_Molecule() */





void CONECT_line_into_ConnectAtomNum(line,Ncon_atom,con_atom_num_in_file)
  char *line;
  int  *Ncon_atom;
  int  *con_atom_num_in_file;  /* array[0..6] */
{
  int Lline;
  char B[100];
  Lline = strlen(line);

/*
  012345678901234567890123456789012345678901234567890
            1         2         3         4
  CONECT    1    9
  CONECT    2    9
  CONECT    3    5   13   14   15
  CONECT    1    2    3    4    8
  CONECT 2802 2803
  CONECT 2803 2802 2804 2808
  CONECT  63353903                                                                
  CONECT1217454038                                                                
  CONECT5385953860538615386253866        

*/
  *Ncon_atom = 0;
  if (Lline>10) {Get_Part_Of_Line(B,line, 6,10); con_atom_num_in_file[0] = atoi(B); *Ncon_atom = 1;}
  if (Lline>15) {Get_Part_Of_Line(B,line,11,15); con_atom_num_in_file[1] = atoi(B); *Ncon_atom = 2;}
  if (Lline>20) {Get_Part_Of_Line(B,line,16,20); con_atom_num_in_file[2] = atoi(B); *Ncon_atom = 3;}
  if (Lline>25) {Get_Part_Of_Line(B,line,21,25); con_atom_num_in_file[3] = atoi(B); *Ncon_atom = 4;}
  if (Lline>30) {Get_Part_Of_Line(B,line,26,30); con_atom_num_in_file[4] = atoi(B); *Ncon_atom = 5;}
  if (Lline>35) {Get_Part_Of_Line(B,line,31,35); con_atom_num_in_file[5] = atoi(B); *Ncon_atom = 6;}
  if (Lline>40) {Get_Part_Of_Line(B,line,36,40); con_atom_num_in_file[6] = atoi(B); *Ncon_atom = 7;}

/*
  printf("#CONECT_line_into_ConnectAtomNum('%s') Ncon_atom %d\n",line,*Ncon_atom);
 */

} /* end of CONECT_line_into_ConnectAtomNum() */


